// Curated, attributed wisdom for traders — legendary speculators, Market
// Wizards, war strategists, stoics and champions. No anonymous clichés,
// no motivational-poster filler; every line earns its place.

export interface Quote {
  text: string;
  author: string;
}

export const TRADING_QUOTES: Quote[] = [
  // ═══════════════════════════════════════════════════════════════════
  // KILLER INSTINCT — conviction, aggression, going for the jugular
  // ═══════════════════════════════════════════════════════════════════
  { text: "Soros taught me that when you have tremendous conviction on a trade, you have to go for the jugular.", author: "Stanley Druckenmiller" },
  { text: "It takes courage to be a pig.", author: "Stanley Druckenmiller" },
  { text: "When you're right on something, you can't own enough.", author: "Stanley Druckenmiller" },
  { text: "I like putting all my eggs in one basket and then watching the basket very carefully.", author: "Stanley Druckenmiller" },
  { text: "I believe the very best money is made at the market turns.", author: "Paul Tudor Jones" },
  { text: "Where you want to be is always in control, never wishing, always trading.", author: "Paul Tudor Jones" },
  { text: "Adapt, evolve, compete or die.", author: "Paul Tudor Jones" },
  { text: "I am the animal at the head of the pack. I either get eaten or I get the good grass.", author: "David Tepper" },
  { text: "Opportunities multiply as they are seized.", author: "Sun Tzu" },
  { text: "Let your plans be dark and impenetrable as night, and when you move, fall like a thunderbolt.", author: "Sun Tzu" },
  { text: "Never was anything great achieved without danger.", author: "Niccolò Machiavelli" },
  { text: "Great deeds are usually wrought at great risks.", author: "Herodotus" },
  { text: "The only reason a warrior is alive is to fight, and the only reason a warrior fights is to win.", author: "Miyamoto Musashi" },
  { text: "In battle, if you make your opponent flinch, you have already won.", author: "Miyamoto Musashi" },
  { text: "Attackers may sometimes regret bad moves, but it is much worse to forever regret an opportunity you allowed to pass by.", author: "Garry Kasparov" },
  { text: "Being second is to be the first of the ones who lose.", author: "Ayrton Senna" },
  { text: "There is nothing impossible to him who will try.", author: "Alexander the Great" },
  { text: "In any moment of decision, the best thing you can do is the right thing, the next best thing is the wrong thing, and the worst thing you can do is nothing.", author: "Theodore Roosevelt" },
  { text: "Far better it is to dare mighty things, to win glorious triumphs, even though checkered by failure, than to rank with those poor spirits who neither enjoy much nor suffer much.", author: "Theodore Roosevelt" },
  { text: "A good plan violently executed now is better than a perfect plan executed next week.", author: "George S. Patton" },
  { text: "Accept the challenges so that you can feel the exhilaration of victory.", author: "George S. Patton" },
  { text: "Take time to deliberate, but when the time for action comes, stop thinking and go in.", author: "Napoleon Bonaparte" },
  { text: "Never interrupt your enemy when he is making a mistake.", author: "Napoleon Bonaparte" },
  { text: "The battlefield is a scene of constant chaos. The winner will be the one who controls that chaos, both his own and the enemy's.", author: "Napoleon Bonaparte" },
  { text: "Be willing to make decisions. Don't fall victim to the ready-aim-aim-aim syndrome. You must be willing to fire.", author: "T. Boone Pickens" },
  { text: "If you're going to hunt elephants, don't get off the trail for a rabbit.", author: "T. Boone Pickens" },
  { text: "The hardest thing over the years has been having the courage to go against the dominant wisdom of the time.", author: "Michael Steinhardt" },
  { text: "Tell me something important that the market doesn't know.", author: "Michael Steinhardt" },
  { text: "We're not here to take part — we're here to take over.", author: "Conor McGregor" },

  // ═══════════════════════════════════════════════════════════════════
  // RISK & SURVIVAL — defense first, live to fight tomorrow
  // ═══════════════════════════════════════════════════════════════════
  { text: "The most important rule of trading is to play great defense, not great offense.", author: "Paul Tudor Jones" },
  { text: "Every day I assume every position I have is wrong.", author: "Paul Tudor Jones" },
  { text: "If I have positions going against me, I get right out; if they are going for me, I keep them.", author: "Paul Tudor Jones" },
  { text: "I know that to be successful, I have to be frightened.", author: "Paul Tudor Jones" },
  { text: "If you don't bet, you can't win. If you lose all your chips, you can't bet.", author: "Larry Hite" },
  { text: "Frankly, I don't see markets; I see risks, rewards, and money.", author: "Larry Hite" },
  { text: "Throughout my financial career, I have continually witnessed examples of other people ruined by a failure to respect risk.", author: "Larry Hite" },
  { text: "Novice traders trade five to ten times too big.", author: "Bruce Kovner" },
  { text: "I know where I'm getting out before I get in.", author: "Bruce Kovner" },
  { text: "Never average losses.", author: "Jesse Livermore" },
  { text: "If you can't sleep at night because of your stock market position, then you have gone too far.", author: "Jesse Livermore" },
  { text: "The speculator's deadly enemies are: ignorance, greed, fear and hope.", author: "Jesse Livermore" },
  { text: "Play the market only when all factors are in your favor.", author: "Jesse Livermore" },
  { text: "If you can't take a small loss, sooner or later you will take the mother of all losses.", author: "Ed Seykota" },
  { text: "There are old traders and there are bold traders, but there are very few old, bold traders.", author: "Ed Seykota" },
  { text: "Risk no more than you can afford to lose, and also risk enough so that a win is meaningful.", author: "Ed Seykota" },
  { text: "When I get hurt in the market, I get the hell out. It doesn't matter at all where the market is trading.", author: "Randy McKay" },
  { text: "Limit your size in any position so that fear does not become the prevailing instinct guiding your judgment.", author: "Joe Vidich" },
  { text: "Amateurs go broke taking large losses; professionals go broke taking small profits.", author: "William Eckhardt" },
  { text: "Don't think about what the market's going to do; you have absolutely no control over that. Think about what you're going to do if it gets there.", author: "William Eckhardt" },
  { text: "Amateurs think about how much money they can make. Professionals think about how much money they could lose.", author: "Jack Schwager" },
  { text: "Letting losses run is the most serious mistake made by most investors.", author: "William O'Neil" },
  { text: "The whole secret to winning big in the stock market is not to be right all the time, but to lose the least amount possible when you're wrong.", author: "William O'Neil" },
  { text: "Accepting losses is the most important single investment device to insure safety of capital.", author: "Gerald Loeb" },
  { text: "Be careful of leverage. It can go against you.", author: "Walter Schloss" },
  { text: "You only find out who is swimming naked when the tide goes out.", author: "Warren Buffett" },
  { text: "Successful investing is about managing risk, not avoiding it.", author: "Benjamin Graham" },
  { text: "The market can remain irrational longer than you can remain solvent.", author: "John Maynard Keynes" },
  { text: "Invincibility lies in the defence; the possibility of victory in the attack.", author: "Sun Tzu" },
  { text: "He will win who knows when to fight and when not to fight.", author: "Sun Tzu" },
  { text: "Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win.", author: "Sun Tzu" },

  // ═══════════════════════════════════════════════════════════════════
  // DISCIPLINE & PATIENCE — the waiting is the trade
  // ═══════════════════════════════════════════════════════════════════
  { text: "It was never my thinking that made the big money for me. It was my sitting. Men who can both be right and sit tight are uncommon.", author: "Jesse Livermore" },
  { text: "Money is made by sitting, not trading.", author: "Jesse Livermore" },
  { text: "The desire for constant action irrespective of underlying conditions is responsible for many losses on Wall Street.", author: "Jesse Livermore" },
  { text: "Don't take action with a trade until the market, itself, confirms your opinion.", author: "Jesse Livermore" },
  { text: "The big money is not in the buying and the selling, but in the waiting.", author: "Charlie Munger" },
  { text: "It's waiting that helps you as an investor, and a lot of people just can't stand to wait.", author: "Charlie Munger" },
  { text: "The first rule of compounding: never interrupt it unnecessarily.", author: "Charlie Munger" },
  { text: "You need patience, discipline, and an agility to take losses and adversity without going crazy.", author: "Charlie Munger" },
  { text: "The stock market is a device for transferring money from the impatient to the patient.", author: "Warren Buffett" },
  { text: "Opportunities come infrequently. When it rains gold, put out the bucket, not the thimble.", author: "Warren Buffett" },
  { text: "The difference between successful people and really successful people is that really successful people say no to almost everything.", author: "Warren Buffett" },
  { text: "Games are won by players who focus on the playing field — not by those whose eyes are glued to the scoreboard.", author: "Warren Buffett" },
  { text: "If most traders would learn to sit on their hands 50 percent of the time, they would make a lot more money.", author: "Bill Lipschutz" },
  { text: "Sometimes the hardest thing to do is to do nothing.", author: "David Tepper" },
  { text: "I just wait until there is money lying in the corner, and all I have to do is go over and pick it up.", author: "Jim Rogers" },
  { text: "Don't do anything until you know what you're doing.", author: "Jim Rogers" },
  { text: "In investing, activity is almost always in surplus.", author: "Charles Ellis" },
  { text: "Time is your friend; impulse is your enemy.", author: "Jack Bogle" },
  { text: "Investing should be more like watching paint dry or watching grass grow. If you want excitement, take $800 and go to Las Vegas.", author: "Paul Samuelson" },
  { text: "If investing is entertaining, if you're having fun, you're probably not making any money. Good investing is boring.", author: "George Soros" },
  { text: "He who wishes to become rich from this game must have both money and patience.", author: "José de la Vega" },
  { text: "Profits on the exchange are the treasures of goblins.", author: "José de la Vega" },
  { text: "Good trading should be boring.", author: "Jack Schwager" },
  { text: "Amateurs look for challenges; professionals look for easy trades.", author: "Alexander Elder" },
  { text: "Losers get high from the action; the pros look for the best odds.", author: "Alexander Elder" },
  { text: "Discipline equals freedom.", author: "Jocko Willink" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "We must all suffer from one of two pains: the pain of discipline or the pain of regret.", author: "Jim Rohn" },
  { text: "Discipline is doing what you hate to do, but nonetheless doing it like you love it.", author: "Mike Tyson" },
  { text: "Do nothing that is of no use.", author: "Miyamoto Musashi" },
  { text: "Ponder and deliberate before you make a move.", author: "Sun Tzu" },
  { text: "Winning is a habit. Unfortunately, so is losing.", author: "Vince Lombardi" },
  { text: "Rest at the end, not in the middle.", author: "Kobe Bryant" },

  // ═══════════════════════════════════════════════════════════════════
  // LOSSES & RESILIENCE — taking hits, getting back up
  // ═══════════════════════════════════════════════════════════════════
  { text: "A loss never bothers me after I take it. I forget it overnight. But being wrong — not taking the loss — that is what does damage to the pocketbook and to the soul.", author: "Jesse Livermore" },
  { text: "Learn to take losses. The most important thing in making money is not letting your losses get out of hand.", author: "Marty Schwartz" },
  { text: "I turned from a loser to a winner when I stopped caring about being right and started caring about making money.", author: "Marty Schwartz" },
  { text: "Honor thy stop.", author: "Marty Schwartz" },
  { text: "Bottom fishing is one of the most expensive forms of gambling.", author: "Marty Schwartz" },
  { text: "The elements of good trading are: cutting losses, cutting losses, and cutting losses.", author: "Ed Seykota" },
  { text: "Losers average losers.", author: "Paul Tudor Jones" },
  { text: "Trading is very competitive and you have to be able to handle getting your butt kicked.", author: "Paul Tudor Jones" },
  { text: "Failure was a key element to my life's journey.", author: "Paul Tudor Jones" },
  { text: "I'm only rich because I know when I'm wrong.", author: "George Soros" },
  { text: "Risk taking is painful. Either you are willing to bear the pain yourself or you try to pass it on to others.", author: "George Soros" },
  { text: "Being wrong is acceptable, but staying wrong is totally unacceptable.", author: "Mark Minervini" },
  { text: "Losses are a function of risk, and risk is a function of choice.", author: "Mark Minervini" },
  { text: "When you have a losing streak, cut back, get smaller.", author: "Richard Dennis" },
  { text: "If you personalize losses, you can't trade.", author: "Bruce Kovner" },
  { text: "Perhaps the most important rule is to hold on to your winners and cut your losers.", author: "Michael Marcus" },
  { text: "Being a successful trader also takes courage: the courage to try, the courage to fail, the courage to succeed, and the courage to keep on going when the going gets tough.", author: "Michael Marcus" },
  { text: "It sure is hell to make that much money and give it back.", author: "Bill Lipschutz" },
  { text: "The golden rule of trading: cut your losses short and let your profits run.", author: "Van K. Tharp" },
  { text: "Pain plus reflection equals progress.", author: "Ray Dalio" },
  { text: "If you're not failing, you're not pushing your limits, and if you're not pushing your limits, you're not maximizing your potential.", author: "Ray Dalio" },
  { text: "Every time you confront something painful, you are at a potentially important juncture in your life.", author: "Ray Dalio" },
  { text: "Experience is what you got when you didn't get what you wanted.", author: "Howard Marks" },
  { text: "From success you learn absolutely nothing. From failure and setbacks conclusions can be drawn.", author: "Niki Lauda" },
  { text: "I've missed more than 9,000 shots in my career. I've failed over and over and over again in my life. And that is why I succeed.", author: "Michael Jordan" },
  { text: "Obstacles don't have to stop you. If you run into a wall, don't turn around and give up.", author: "Michael Jordan" },
  { text: "It's not whether you get knocked down; it's whether you get up.", author: "Vince Lombardi" },
  { text: "The moment you give up is the moment you let someone else win.", author: "Kobe Bryant" },
  { text: "Everything negative — pressure, challenges — is all an opportunity for me to rise.", author: "Kobe Bryant" },
  { text: "You're never beaten until you admit it.", author: "George S. Patton" },
  { text: "Courage is fear holding on a minute longer.", author: "George S. Patton" },
  { text: "Strength does not come from winning. Your struggles develop your strengths.", author: "Arnold Schwarzenegger" },
  { text: "Suffering is a test. That's all it is.", author: "David Goggins" },
  { text: "Don't stop when you're tired. Stop when you're done.", author: "David Goggins" },
  { text: "It is not because things are difficult that we do not dare; it is because we do not dare that things are difficult.", author: "Seneca" },
  { text: "Difficulties strengthen the mind, as labor does the body.", author: "Seneca" },

  // ═══════════════════════════════════════════════════════════════════
  // PSYCHOLOGY & SELF-MASTERY — the war inside
  // ═══════════════════════════════════════════════════════════════════
  { text: "Don't be a hero. Don't have an ego. The second you think you're very good, you're dead.", author: "Paul Tudor Jones" },
  { text: "The consistency you seek is in your mind, not in the markets.", author: "Mark Douglas" },
  { text: "You don't need to know what's going to happen next to make money.", author: "Mark Douglas" },
  { text: "Anything can happen. Every moment in the market is unique.", author: "Mark Douglas" },
  { text: "Trading is not about being right or wrong.", author: "Mark Douglas" },
  { text: "The hard, cold reality of trading is that every trade has an uncertain outcome.", author: "Mark Douglas" },
  { text: "The less I cared about whether or not I was wrong, the clearer things became.", author: "Mark Douglas" },
  { text: "When you genuinely accept the risks, you will be at peace with any outcome.", author: "Mark Douglas" },
  { text: "If you can learn to create a state of mind that is not affected by the market's behaviour, the struggle will cease to exist.", author: "Mark Douglas" },
  { text: "The best traders have evolved to the point where they believe, without a shred of doubt or internal conflict, that anything can happen.", author: "Mark Douglas" },
  { text: "The marketplace is an expensive place to learn about yourself.", author: "Marty Schwartz" },
  { text: "The most important change in my trading career occurred when I learned to divorce my ego from the trade.", author: "Marty Schwartz" },
  { text: "If you don't know who you are, the stock market is an expensive place to find out.", author: "Adam Smith (George Goodman)" },
  { text: "Win or lose, everybody gets what they want out of the market.", author: "Ed Seykota" },
  { text: "Pride is a great banana peel — as are hope, fear, and greed.", author: "Ed Seykota" },
  { text: "Trading requires skill at reading the markets and at managing your own anxieties.", author: "Ed Seykota" },
  { text: "The key to trading success is emotional discipline. If intelligence were the key, there would be a lot more people making money trading.", author: "Victor Sperandeo" },
  { text: "If you're playing for emotional satisfaction, you're bound to lose, because what feels good is often the wrong thing to do.", author: "William Eckhardt" },
  { text: "The people who survive avoid snowball scenarios in which bad trades cause them to become emotionally destabilized.", author: "William Eckhardt" },
  { text: "You don't trade the markets; you trade your beliefs about the markets.", author: "Van K. Tharp" },
  { text: "A peak performance trader is totally committed to being the best and doing whatever it takes to be the best.", author: "Van K. Tharp" },
  { text: "The goal of a successful trader is to make the best trades. Money is secondary.", author: "Alexander Elder" },
  { text: "Beginners focus on analysis, but professionals operate in a three-dimensional space: their own feelings and the mass psychology of the markets.", author: "Alexander Elder" },
  { text: "The investor's chief problem, and even his worst enemy, is likely to be himself.", author: "Benjamin Graham" },
  { text: "Individuals who cannot master their emotions are ill-suited to profit from the investment process.", author: "Benjamin Graham" },
  { text: "You are neither right nor wrong because the crowd disagrees with you. You are right because your data and reasoning are right.", author: "Benjamin Graham" },
  { text: "The biggest investing errors come not from analysis, but from psychology.", author: "Howard Marks" },
  { text: "The most important quality for an investor is temperament, not intellect.", author: "Warren Buffett" },
  { text: "A lot of people with high IQs are terrible investors because they've got terrible temperaments.", author: "Charlie Munger" },
  { text: "Envy is a really stupid sin because it's the only one you could never possibly have any fun at.", author: "Charlie Munger" },
  { text: "Everyone has the brainpower to make money in stocks. Not everyone has the stomach.", author: "Peter Lynch" },
  { text: "Far more money has been lost by investors preparing for corrections than has been lost in corrections themselves.", author: "Peter Lynch" },
  { text: "The single most important factor in shaping security markets is public psychology.", author: "Gerald Loeb" },
  { text: "When you're trading well, you have a better mental attitude. When you're trading poorly, you start wishing and hoping.", author: "Monroe Trout" },
  { text: "If trading is your life, it is a torturous kind of excitement. But if you are keeping your life in balance, then it is fun.", author: "Michael Marcus" },
  { text: "Every trader has strengths and weaknesses. You need to be aware of them.", author: "Michael Marcus" },
  { text: "Successful traders constantly ask themselves: What am I doing right? What am I doing wrong?", author: "Bill Lipschutz" },
  { text: "I don't think you can consistently be a winning trader if you're banking on being right more than 50 percent of the time.", author: "Bill Lipschutz" },
  { text: "Psychologically, you have to have confidence in yourself, and this confidence should be based on fact.", author: "Bobby Fischer" },
  { text: "What makes a decision great is not that it has a great outcome. A great decision is the result of a good process.", author: "Annie Duke" },
  { text: "Look around the table. If you don't see a sucker, get up, because you're the sucker.", author: "Amarillo Slim" },
  { text: "Don't confuse brains with a bull market.", author: "Humphrey Neill" },
  { text: "When friends are telling you that you are a genius, before you accept their opinion, take a moment to remember what you always thought of their opinions in the past.", author: "Carl Icahn" },
  { text: "Some people get rich studying artificial intelligence. Me, I make money studying natural stupidity.", author: "Carl Icahn" },
  { text: "In life and business, there are two cardinal sins: the first is to act precipitously without thought, and the second is to not act at all.", author: "Carl Icahn" },
  { text: "Become more humble as the market goes your way.", author: "Bernard Baruch" },
  { text: "Whatever failures I have known, whatever errors I have committed, were the consequence of action without thought.", author: "Bernard Baruch" },
  { text: "Every man has a right to his opinion, but no man has a right to be wrong in his facts.", author: "Bernard Baruch" },
  { text: "I have self-doubt. We all have self-doubt. You don't deny it, but you also don't capitulate to it. You embrace it.", author: "Kobe Bryant" },

  // ═══════════════════════════════════════════════════════════════════
  // PROCESS & PREPARATION — the work before the trade
  // ═══════════════════════════════════════════════════════════════════
  { text: "The secret is an unquenchable thirst for information and knowledge.", author: "Paul Tudor Jones" },
  { text: "Confidence comes from preparation. When the pressure is on, you don't rise to the occasion — you fall to your level of preparation.", author: "Mark Minervini" },
  { text: "When you trade well, over time the money finds you.", author: "Mark Minervini" },
  { text: "The goal is not to buy at the cheapest price but to sell your stock for much more than the price you paid.", author: "Mark Minervini" },
  { text: "I believe in analysis and not forecasting.", author: "Nicolas Darvas" },
  { text: "I made up my mind to buy high and sell higher.", author: "Nicolas Darvas" },
  { text: "There are no good or bad stocks, there are only rising and falling stocks.", author: "Nicolas Darvas" },
  { text: "I knew now that I had to keep rigidly to the system I had carved out for myself.", author: "Nicolas Darvas" },
  { text: "All stocks are bad. There are no good stocks unless they go up in price.", author: "William O'Neil" },
  { text: "Ninety percent of the people in the stock market, professionals and amateurs alike, simply haven't done enough homework.", author: "William O'Neil" },
  { text: "The game taught me the game.", author: "Jesse Livermore" },
  { text: "There is only one side of the market and it is not the bull side or the bear side, but the right side.", author: "Jesse Livermore" },
  { text: "A prudent speculator never argues with the tape.", author: "Jesse Livermore" },
  { text: "Fundamentalists who say they are not going to pay attention to the charts are like a doctor who says he's not going to take a patient's temperature.", author: "Bruce Kovner" },
  { text: "The best trades are the ones in which you have all three things going for you: fundamentals, technicals, and market tone.", author: "Michael Marcus" },
  { text: "Do more of what works and less of what doesn't.", author: "Steve Clark" },
  { text: "Traders who are successful over the long run adapt. If they do use rules, and you meet them ten years later, they will have broken those rules. Why? Because the world changed.", author: "Colm O'Shea" },
  { text: "Virtually every successful trader I know ultimately ended up with a trading style suited to his personality.", author: "Randy McKay" },
  { text: "There are a million ways to make money in the markets. The irony is that they are all very difficult to find.", author: "Jack Schwager" },
  { text: "The single most important element uniting all market wizards: they have found an approach that fits their personality.", author: "Jack Schwager" },
  { text: "Trading has taught me not to take the conventional wisdom for granted.", author: "Richard Dennis" },
  { text: "I could publish my trading rules in the newspaper and no one would follow them. The key is consistency and discipline.", author: "Richard Dennis" },
  { text: "Trading is a business. Treat it like one.", author: "Tom Basso" },
  { text: "Investment psychology is by far the more important element, followed by risk control, with the least important consideration being where you buy and sell.", author: "Tom Basso" },
  { text: "We search through historical data looking for anomalous patterns that we would not expect to occur at random.", author: "Jim Simons" },
  { text: "Be guided by beauty.", author: "Jim Simons" },
  { text: "Work with the smartest people you can.", author: "Jim Simons" },
  { text: "Don't give up easily; stick with it.", author: "Jim Simons" },
  { text: "Know what you own, and know why you own it.", author: "Peter Lynch" },
  { text: "The person that turns over the most rocks wins the game.", author: "Peter Lynch" },
  { text: "Take a simple idea and take it seriously.", author: "Charlie Munger" },
  { text: "Those who keep learning will keep rising in life.", author: "Charlie Munger" },
  { text: "Knowing what you don't know is more useful than being brilliant.", author: "Charlie Munger" },
  { text: "Invert, always invert.", author: "Charlie Munger" },
  { text: "The ability to work hard for days on end without losing focus is a talent.", author: "Garry Kasparov" },
  { text: "Tactics flow from a superior position.", author: "Bobby Fischer" },
  { text: "The fight is won or lost far away from witnesses — behind the lines, in the gym, and out there on the road, long before I dance under those lights.", author: "Muhammad Ali" },
  { text: "I hated every minute of training, but I said: don't quit. Suffer now and live the rest of your life as a champion.", author: "Muhammad Ali" },
  { text: "I've always believed that if you put in the work, the results will come.", author: "Michael Jordan" },
  { text: "I fear not the man who has practiced 10,000 kicks once, but the man who has practiced one kick 10,000 times.", author: "Bruce Lee" },
  { text: "Knowing is not enough, we must apply. Willing is not enough, we must do.", author: "Bruce Lee" },
  { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
  { text: "There's no talent here, this is hard work. This is an obsession.", author: "Conor McGregor" },
  { text: "I have no idols. I admire work, dedication and competence.", author: "Ayrton Senna" },
  { text: "It may seem difficult at first, but everything is difficult at first.", author: "Miyamoto Musashi" },
  { text: "Perceive that which cannot be seen with the eye.", author: "Miyamoto Musashi" },
  { text: "No man was ever wise by chance.", author: "Seneca" },
  { text: "Luck is what happens when preparation meets opportunity.", author: "Seneca" },

  // ═══════════════════════════════════════════════════════════════════
  // CONTRARIAN EDGE — crowds, cycles, betting on the unexpected
  // ═══════════════════════════════════════════════════════════════════
  { text: "Be fearful when others are greedy, and greedy when others are fearful.", author: "Warren Buffett" },
  { text: "Money is made by discounting the obvious and betting on the unexpected.", author: "George Soros" },
  { text: "The four most dangerous words in investing are: 'this time it's different.'", author: "Sir John Templeton" },
  { text: "Bull markets are born on pessimism, grown on skepticism, mature on optimism, and die on euphoria.", author: "Sir John Templeton" },
  { text: "The time of maximum pessimism is the best time to buy, and the time of maximum optimism is the best time to sell.", author: "Sir John Templeton" },
  { text: "It is impossible to produce superior performance unless you do something different from the majority.", author: "Sir John Templeton" },
  { text: "Rule number one: most things will prove to be cyclical. Rule number two: some of the greatest opportunities for gain and loss come when other people forget rule number one.", author: "Howard Marks" },
  { text: "The most dangerous thing is to buy something at the peak of its popularity.", author: "Howard Marks" },
  { text: "You can't predict. You can prepare.", author: "Howard Marks" },
  { text: "Being too far ahead of your time is indistinguishable from being wrong.", author: "Howard Marks" },
  { text: "Move forward, but with caution.", author: "Howard Marks" },
  { text: "In investing, what is comfortable is rarely profitable.", author: "Rob Arnott" },
  { text: "When the time comes to buy, you won't want to.", author: "Walter Deemer" },
  { text: "The intelligent investor is a realist who sells to optimists and buys from pessimists.", author: "Benjamin Graham" },
  { text: "In the short run the market is a voting machine, but in the long run it is a weighing machine.", author: "Benjamin Graham" },
  { text: "The main purpose of the stock market is to make fools of as many people as possible.", author: "Bernard Baruch" },
  { text: "Don't try to buy at the bottom and sell at the top. It can't be done — except by liars.", author: "Bernard Baruch" },
  { text: "What seems too high and risky usually goes higher; what seems low and cheap usually goes lower.", author: "William O'Neil" },
  { text: "It is ludicrous to believe that asset bubbles can only be recognized in hindsight.", author: "Michael Burry" },
  { text: "I try to buy shares of unpopular companies when they look like road kill, and sell them when they've been polished up a bit.", author: "Michael Burry" },
  { text: "The stock market is filled with individuals who know the price of everything, but the value of nothing.", author: "Philip Fisher" },
  { text: "Value investing is the marriage of a contrarian streak and a calculator.", author: "Seth Klarman" },
  { text: "The single greatest edge an investor can have is a long-term orientation.", author: "Seth Klarman" },
  { text: "When the facts change, I change my mind. What do you do, sir?", author: "John Maynard Keynes" },
  { text: "Successful investing is anticipating the anticipations of others.", author: "John Maynard Keynes" },
  { text: "The markets are the same now as they were five to ten years ago because they keep changing — just like they did then.", author: "Ed Seykota" },
  { text: "The trend is your friend except at the end where it bends.", author: "Ed Seykota" },
  { text: "Markets change. People adapt.", author: "David Tepper" },
  { text: "Those who keep their heads while others are panicking do well.", author: "David Tepper" },
  { text: "You should expect the unexpected in this business; expect the extreme. Don't think in terms of boundaries.", author: "Richard Dennis" },
  { text: "Choosing individual stocks without any idea of what you're looking for is like running through a dynamite factory with a burning match. You may live, but you're still an idiot.", author: "Joel Greenblatt" },
  { text: "The stock exchange reacts like a drunk man: it cries at good news and laughs at bad news.", author: "André Kostolany" },
  { text: "Stock market gains are pain money: first comes the pain, then the money.", author: "André Kostolany" },

  // ═══════════════════════════════════════════════════════════════════
  // MARKET TRUTHS — the nature of the game
  // ═══════════════════════════════════════════════════════════════════
  { text: "The market is never wrong — opinions often are.", author: "Jesse Livermore" },
  { text: "There is nothing new in Wall Street. Whatever happens has happened before and will happen again.", author: "Jesse Livermore" },
  { text: "It's not whether you're right or wrong, but how much money you make when you're right and how much you lose when you're wrong.", author: "George Soros" },
  { text: "The way to build long-term returns is through preservation of capital and home runs.", author: "Stanley Druckenmiller" },
  { text: "Never, ever invest in the present.", author: "Stanley Druckenmiller" },
  { text: "At the end of the day, the most important thing is how good you are at risk control.", author: "Paul Tudor Jones" },
  { text: "Risk comes from not knowing what you're doing.", author: "Warren Buffett" },
  { text: "Rule No. 1: Never lose money. Rule No. 2: Never forget Rule No. 1.", author: "Warren Buffett" },
  { text: "Price is what you pay. Value is what you get.", author: "Warren Buffett" },
  { text: "It takes 20 years to build a reputation and five minutes to ruin it.", author: "Warren Buffett" },
  { text: "It is remarkable how much long-term advantage people like us have gotten by trying to be consistently not stupid, instead of trying to be very intelligent.", author: "Charlie Munger" },
  { text: "Don't get caught in a position where you can lose a great deal of money for reasons you don't understand.", author: "Bruce Kovner" },
  { text: "Whenever I enter a position, I have a predetermined stop. That's the only way I can sleep.", author: "Bruce Kovner" },
  { text: "The key to making money in stocks is not to get scared out of them.", author: "Peter Lynch" },
  { text: "In this business, if you're good, you're right six times out of ten. You're never right nine times out of ten.", author: "Peter Lynch" },
  { text: "You get recessions, you have stock market declines. If you don't understand that's going to happen, then you're not ready and you won't do well in the markets.", author: "Peter Lynch" },
  { text: "He who lives by the crystal ball will eat shattered glass.", author: "Ray Dalio" },
  { text: "Truth — an accurate understanding of reality — is the essential foundation for any good outcome.", author: "Ray Dalio" },
  { text: "The biggest mistake investors make is to believe that what happened in the recent past is likely to persist.", author: "Ray Dalio" },
  { text: "It is far more sound to be approximately right than precisely wrong.", author: "Nassim Nicholas Taleb" },
  { text: "Don't tell me what you think — tell me what you have in your portfolio.", author: "Nassim Nicholas Taleb" },
  { text: "Missing a train is only painful if you run after it.", author: "Nassim Nicholas Taleb" },
  { text: "Courage is the only virtue you cannot fake.", author: "Nassim Nicholas Taleb" },
  { text: "If you take risks and face your fate with dignity, there is nothing you can do that makes you small.", author: "Nassim Nicholas Taleb" },
  { text: "The stock market is people trying to read the future.", author: "Bernard Baruch" },
  { text: "It's not about being right or wrong; it's about how much you make when right and how much you lose when wrong.", author: "Stanley Druckenmiller" },
  { text: "I usually ignore advice from other traders, especially the ones who believe they are on to a 'sure thing'.", author: "Ed Seykota" },
  { text: "Everyone has a plan until they get punched in the mouth.", author: "Mike Tyson" },

  // ═══════════════════════════════════════════════════════════════════
  // STOIC OPERATING SYSTEM — control what you can
  // ═══════════════════════════════════════════════════════════════════
  { text: "You have power over your mind — not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
  { text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius" },
  { text: "Confine yourself to the present.", author: "Marcus Aurelius" },
  { text: "You could leave life right now. Let that determine what you do and say and think.", author: "Marcus Aurelius" },
  { text: "The soul becomes dyed with the color of its thoughts.", author: "Marcus Aurelius" },
  { text: "If it is not right, do not do it; if it is not true, do not say it.", author: "Marcus Aurelius" },
  { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
  { text: "Every night before going to sleep, we must ask ourselves: what weakness did I overcome today? What virtue did I acquire?", author: "Seneca" },
  { text: "It's not what happens to you, but how you react to it that matters.", author: "Epictetus" },
  { text: "No man is free who is not master of himself.", author: "Epictetus" },
  { text: "First say to yourself what you would be; and then do what you have to do.", author: "Epictetus" },
  { text: "Circumstances don't make the man, they only reveal him to himself.", author: "Epictetus" },
  { text: "Today is victory over yourself of yesterday; tomorrow is your victory over lesser men.", author: "Miyamoto Musashi" },
  { text: "Think lightly of yourself and deeply of the world.", author: "Miyamoto Musashi" },
  { text: "Do not pray for an easy life, pray for the strength to endure a difficult one.", author: "Bruce Lee" },
  { text: "A goal is not always meant to be reached; it often serves simply as something to aim at.", author: "Bruce Lee" },
  { text: "Every battle is won before it is ever fought.", author: "Sun Tzu" },
  { text: "In the midst of chaos, there is also opportunity.", author: "Sun Tzu" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "There is nothing to fear from truth.", author: "Ray Dalio" },
  { text: "Radical open-mindedness and radical transparency are invaluable.", author: "Ray Dalio" },
  { text: "You are in danger of living a life so comfortable and soft that you will die without ever realizing your true potential.", author: "David Goggins" },
  { text: "The worst thing I can be is the same as everybody else.", author: "Arnold Schwarzenegger" },
  { text: "He who is not courageous enough to take risks will accomplish nothing in life.", author: "Muhammad Ali" },
  { text: "Some people want it to happen, some wish it would happen, others make it happen.", author: "Michael Jordan" },
  { text: "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will.", author: "Vince Lombardi" },
  { text: "Luck plays a meaningful role in everyone's lives.", author: "Jim Simons" },
];
