import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import dbConnect from "@/lib/mongodb";
import { NewsSentimentReportModel } from "@/lib/models/NewsSentimentReport";

export const runtime = "nodejs";

export async function GET(_req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const session = await auth();
  if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { id } = await params;
  await dbConnect();
  // Visible to any authenticated user, not just the generator.
  const report = await NewsSentimentReportModel.findById(id).lean();
  if (!report) return NextResponse.json({ error: "Not found" }, { status: 404 });
  return NextResponse.json(report);
}

export async function DELETE(_req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const session = await auth();
  if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { id } = await params;
  await dbConnect();

  const doc = await NewsSentimentReportModel.findById(id);
  if (!doc) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const userEmail = session.user.email;
  const isOwner = doc.generatedBy && userEmail && doc.generatedBy.toLowerCase() === userEmail.toLowerCase();
  const isAdmin = session.user.role === "admin";
  if (!isOwner && !isAdmin) {
    return NextResponse.json({ error: "Forbidden: You can only delete reports generated by you" }, { status: 403 });
  }

  await NewsSentimentReportModel.findByIdAndDelete(id);
  return NextResponse.json({ ok: true });
}
