import {
  // Fitness
  Dumbbell, Bike, Flame, Activity, Footprints, PersonStanding, Weight, Swords,
  HeartPulse, Timer, Zap, Wind, Sun, Waves,
  // Health
  Heart, Stethoscope, Pill, Droplets, Eye, Brain, Thermometer, TestTube,
  Microscope, Syringe, Dna, FlaskConical,
  // Food
  Apple, Utensils, Coffee, UtensilsCrossed, Pizza, Salad, Egg, Cookie,
  Sandwich, Wine, Milk, Carrot, Wheat, Citrus, IceCreamCone,
  // Sleep
  Moon, Bed, BedDouble, CloudMoon, Sunrise, Sunset,
  // Mind
  Smile, Leaf, Sprout, Gem, Puzzle, Sparkle, HeartHandshake, Flower2, PawPrint, Globe,
  // Finance
  DollarSign, PiggyBank, TrendingUp, TrendingDown, CreditCard, Wallet, Coins,
  ChartBar, ChartLine, Landmark, Briefcase, Receipt,
  // Learning
  BookOpen, GraduationCap, Lightbulb, PenLine, Code, Library, Telescope,
  Feather, Map, Calculator, Languages, BookMarked, NotebookPen,
  // Social
  Users, MessageCircle, Phone, Mail, Video, UserPlus, Share2, Handshake, PartyPopper,
  // Productivity
  Target, Trophy, Star, Rocket, SquareCheck, ClipboardList, Flag, Bell,
  AlarmClock, Gauge, ListTodo, LayoutDashboard, Kanban,
  // Lifestyle
  Music, Camera, Home, ShoppingCart, Smartphone, Gamepad2, Headphones, Tv,
  Car, Plane, Scissors, Brush, Palette, Shirt, Watch, Trees, Mountain,
  // 500 Additional
  AArrowDown, AArrowUp, ALargeSmall, Accessibility, ActivitySquare, AirVent, Airplay, AlarmCheck, AlarmClockCheck, AlarmClockMinus, AlarmClockOff, AlarmClockPlus, AlarmMinus, AlarmPlus, AlarmSmoke, Album, AlertCircle, AlertOctagon, AlertTriangle, AlignCenter, AlignCenterHorizontal, AlignCenterVertical, AlignEndHorizontal, AlignEndVertical, AlignHorizontalDistributeCenter, AlignHorizontalDistributeEnd, AlignHorizontalDistributeStart, AlignHorizontalJustifyCenter, AlignHorizontalJustifyEnd, AlignHorizontalJustifyStart, AlignHorizontalSpaceAround, AlignHorizontalSpaceBetween, AlignJustify, AlignLeft, AlignRight, AlignStartHorizontal, AlignStartVertical, AlignVerticalDistributeCenter, AlignVerticalDistributeEnd, AlignVerticalDistributeStart, AlignVerticalJustifyCenter, AlignVerticalJustifyEnd, AlignVerticalJustifyStart, AlignVerticalSpaceAround, AlignVerticalSpaceBetween, Ambulance, Ampersand, Ampersands, Amphora, Anchor, Angry, Annoyed, Antenna, Anvil, Aperture, AppWindow, AppWindowMac, Archive, ArchiveRestore, ArchiveX, AreaChart, Armchair, ArrowBigDown, ArrowBigDownDash, ArrowBigLeft, ArrowBigLeftDash, ArrowBigRight, ArrowBigRightDash, ArrowBigUp, ArrowBigUpDash, ArrowDown, ArrowDown01, ArrowDown10, ArrowDownAZ, ArrowDownAz, ArrowDownCircle, ArrowDownFromLine, ArrowDownLeft, ArrowDownLeftFromCircle, ArrowDownLeftFromSquare, ArrowDownLeftSquare, ArrowDownNarrowWide, ArrowDownRight, ArrowDownRightFromCircle, ArrowDownRightFromSquare, ArrowDownRightSquare, ArrowDownSquare, ArrowDownToDot, ArrowDownToLine, ArrowDownUp, ArrowDownWideNarrow, ArrowDownZA, ArrowDownZa, ArrowLeft, ArrowLeftCircle, ArrowLeftFromLine, ArrowLeftRight, ArrowLeftSquare, ArrowLeftToLine, ArrowRight, ArrowRightCircle, ArrowRightFromLine, ArrowRightLeft, ArrowRightSquare, ArrowRightToLine, ArrowUp, ArrowUp01, ArrowUp10, ArrowUpAZ, ArrowUpAz, ArrowUpCircle, ArrowUpDown, ArrowUpFromDot, ArrowUpFromLine, ArrowUpLeft, ArrowUpLeftFromCircle, ArrowUpLeftFromSquare, ArrowUpLeftSquare, ArrowUpNarrowWide, ArrowUpRight, ArrowUpRightFromCircle, ArrowUpRightFromSquare, ArrowUpRightSquare, ArrowUpSquare, ArrowUpToLine, ArrowUpWideNarrow, ArrowUpZA, ArrowUpZa, ArrowsUpFromLine, Asterisk, AsteriskSquare, AtSign, Atom, AudioLines, AudioWaveform, Award, Axe, Axis3D, Axis3d, Baby, Backpack, Badge, BadgeAlert, BadgeCent, BadgeCheck, BadgeDollarSign, BadgeEuro, BadgeHelp, BadgeIndianRupee, BadgeInfo, BadgeJapaneseYen, BadgeMinus, BadgePercent, BadgePlus, BadgePoundSterling, BadgeQuestionMark, BadgeRussianRuble, BadgeSwissFranc, BadgeTurkishLira, BadgeX, BaggageClaim, Balloon, Ban, Banana, Bandage, Banknote, BanknoteArrowDown, BanknoteArrowUp, BanknoteX, BarChart, BarChart2, BarChart3, BarChart4, BarChartBig, BarChartHorizontal, BarChartHorizontalBig, Barcode, Barrel, Baseline, Bath, Battery, BatteryCharging, BatteryFull, BatteryLow, BatteryMedium, BatteryPlus, BatteryWarning, Beaker, Bean, BeanOff, BedSingle, Beef, BeefOff, Beer, BeerOff, BellDot, BellElectric, BellMinus, BellOff, BellPlus, BellRing, BetweenHorizonalEnd, BetweenHorizonalStart, BetweenHorizontalEnd, BetweenHorizontalStart, BetweenVerticalEnd, BetweenVerticalStart, BicepsFlexed, Binary, Binoculars, Biohazard, Bird, Birdhouse, Bitcoin, Blend, Blinds, Blocks, Bluetooth, BluetoothConnected, BluetoothOff, BluetoothSearching, Bold, Bolt, Bomb, Bone, Book, BookA, BookAlert, BookAudio, BookCheck, BookCopy, BookDashed, BookDown, BookHeadphones, BookHeart, BookImage, BookKey, BookLock, BookMinus, BookOpenCheck, BookOpenText, BookPlus, BookSearch, BookTemplate, BookText, BookType, BookUp, BookUp2, BookUser, BookX, Bookmark, BookmarkCheck, BookmarkMinus, BookmarkOff, BookmarkPlus, BookmarkX, BoomBox, Bot, BotMessageSquare, BotOff, BottleWine, BowArrow, Box, BoxSelect, Boxes, Braces, Brackets, BrainCircuit, BrainCog, BrickWall, BrickWallFire, BrickWallShield, BriefcaseBusiness, BriefcaseConveyorBelt, BriefcaseMedical, BringToFront, BrushCleaning, Bubbles, Bug, BugOff, BugPlay, Building, Building2, Bus, BusFront, Cable, CableCar, Cake, CakeSlice, Calendar, Calendar1, CalendarArrowDown, CalendarArrowUp, CalendarCheck, CalendarCheck2, CalendarClock, CalendarCog, CalendarDays, CalendarFold, CalendarHeart, CalendarMinus, CalendarMinus2, CalendarOff, CalendarPlus, CalendarPlus2, CalendarRange, CalendarSearch, CalendarSync, CalendarX, CalendarX2, Calendars, CameraOff, CandlestickChart, Candy, CandyCane, CandyOff, Cannabis, CannabisOff, Captions, CaptionsOff, CarFront, CarTaxiFront, Caravan, CardSim, CaseLower, CaseSensitive, CaseUpper, CassetteTape, Cast, Castle, Cat, Cctv, CctvOff, ChartArea, ChartBarBig, ChartBarDecreasing, ChartBarIncreasing, ChartBarStacked, ChartCandlestick, ChartColumn, ChartColumnBig, ChartColumnDecreasing, ChartColumnIncreasing, ChartColumnStacked, ChartGantt, ChartNetwork, ChartNoAxesColumn, ChartNoAxesColumnDecreasing, ChartNoAxesColumnIncreasing, ChartNoAxesCombined, ChartNoAxesGantt, ChartPie, ChartScatter, ChartSpline, Check, CheckCheck, CheckCircle, CheckCircle2, CheckLine, CheckSquare, CheckSquare2, ChefHat, Cherry, ChessBishop, ChessKing, ChessKnight, ChessPawn, ChessQueen, ChessRook, ChevronDown, ChevronDownCircle, ChevronDownSquare, ChevronFirst, ChevronLast, ChevronLeft, ChevronLeftCircle, ChevronLeftSquare, ChevronRight, ChevronRightCircle, ChevronRightSquare, ChevronUp, ChevronUpCircle, ChevronUpSquare, ChevronsDown, ChevronsDownUp, ChevronsLeft, ChevronsLeftRight, ChevronsLeftRightEllipsis, ChevronsRight, ChevronsRightLeft, ChevronsUp, ChevronsUpDown, Church, Cigarette, CigaretteOff, Circle, CircleAlert, CircleArrowDown, CircleArrowLeft, CircleArrowOutDownLeft, CircleArrowOutDownRight, CircleArrowOutUpLeft, CircleArrowOutUpRight, CircleArrowRight, CircleArrowUp, CircleCheck, CircleCheckBig, CircleChevronDown, CircleChevronLeft, CircleChevronRight, CircleChevronUp, CircleDashed, CircleDivide, CircleDollarSign, CircleDot, CircleDotDashed, CircleEllipsis, CircleEqual, CircleFadingArrowUp, CircleFadingPlus, CircleGauge, CircleHelp, CircleMinus, CircleOff, CircleParking, CircleParkingOff, CirclePause, CirclePercent, CirclePile, CirclePlay, CirclePlus, CirclePoundSterling, CirclePower, CircleQuestionMark, CircleSlash, CircleSlash2, CircleSlashed, CircleSmall, CircleStar, CircleStop, CircleUser, CircleUserRound, CircleX, CircuitBoard, Clapperboard, Clipboard, ClipboardCheck, ClipboardClock, ClipboardCopy, ClipboardEdit, ClipboardMinus, ClipboardPaste, ClipboardPen, ClipboardPenLine, ClipboardPlus, ClipboardSignature, ClipboardType, ClipboardX, Clock, Clock1, Clock10, Clock11, Clock12, Clock2, Clock3, Clock4, Clock5, Clock6, Clock7, Clock8, Clock9, ClockAlert, ClockArrowDown, ClockArrowUp, ClockCheck, ClockFading, ClockPlus, ClosedCaption, Cloud, CloudAlert, CloudBackup, CloudCheck, CloudCog, CloudDownload, CloudDrizzle, CloudFog, CloudHail, CloudLightning, CloudMoonRain, CloudOff, CloudRain, CloudRainWind, CloudSnow, CloudSun, CloudSunRain, CloudSync, CloudUpload, Cloudy, Clover, Club
} from "lucide-react";

// ── Icon component map ────────────────────────────────────────────────────

export const HABIT_ICON_MAP = {
  // Fitness
  Dumbbell, Bike, Flame, Activity, Footprints, PersonStanding, Weight, Swords,
  HeartPulse, Timer, Zap, Wind, Sun, Waves,
  // Health
  Heart, Stethoscope, Pill, Droplets, Eye, Brain, Thermometer, TestTube,
  Microscope, Syringe, Dna, FlaskConical,
  // Food
  Apple, Utensils, Coffee, UtensilsCrossed, Pizza, Salad, Egg, Cookie,
  Sandwich, Wine, Milk, Carrot, Wheat, Citrus, IceCreamCone,
  // Sleep
  Moon, Bed, BedDouble, CloudMoon, Sunrise, Sunset,
  // Mind
  Smile, Leaf, Sprout, Gem, Puzzle, Sparkle, HeartHandshake, Flower2, PawPrint, Globe,
  // Finance
  DollarSign, PiggyBank, TrendingUp, TrendingDown, CreditCard, Wallet, Coins,
  ChartBar, ChartLine, Landmark, Briefcase, Receipt,
  // Learning
  BookOpen, GraduationCap, Lightbulb, PenLine, Code, Library, Telescope,
  Feather, Map, Calculator, Languages, BookMarked, NotebookPen,
  // Social
  Users, MessageCircle, Phone, Mail, Video, UserPlus, Share2, Handshake, PartyPopper,
  // Productivity
  Target, Trophy, Star, Rocket, SquareCheck, ClipboardList, Flag, Bell,
  AlarmClock, Gauge, ListTodo, LayoutDashboard, Kanban,
  // Lifestyle
  Music, Camera, Home, ShoppingCart, Smartphone, Gamepad2, Headphones, Tv,
  Car, Plane, Scissors, Brush, Palette, Shirt, Watch, Trees, Mountain,
  // 500 Additional
  AArrowDown, AArrowUp, ALargeSmall, Accessibility, ActivitySquare, AirVent, Airplay, AlarmCheck, AlarmClockCheck, AlarmClockMinus, AlarmClockOff, AlarmClockPlus, AlarmMinus, AlarmPlus, AlarmSmoke, Album, AlertCircle, AlertOctagon, AlertTriangle, AlignCenter, AlignCenterHorizontal, AlignCenterVertical, AlignEndHorizontal, AlignEndVertical, AlignHorizontalDistributeCenter, AlignHorizontalDistributeEnd, AlignHorizontalDistributeStart, AlignHorizontalJustifyCenter, AlignHorizontalJustifyEnd, AlignHorizontalJustifyStart, AlignHorizontalSpaceAround, AlignHorizontalSpaceBetween, AlignJustify, AlignLeft, AlignRight, AlignStartHorizontal, AlignStartVertical, AlignVerticalDistributeCenter, AlignVerticalDistributeEnd, AlignVerticalDistributeStart, AlignVerticalJustifyCenter, AlignVerticalJustifyEnd, AlignVerticalJustifyStart, AlignVerticalSpaceAround, AlignVerticalSpaceBetween, Ambulance, Ampersand, Ampersands, Amphora, Anchor, Angry, Annoyed, Antenna, Anvil, Aperture, AppWindow, AppWindowMac, Archive, ArchiveRestore, ArchiveX, AreaChart, Armchair, ArrowBigDown, ArrowBigDownDash, ArrowBigLeft, ArrowBigLeftDash, ArrowBigRight, ArrowBigRightDash, ArrowBigUp, ArrowBigUpDash, ArrowDown, ArrowDown01, ArrowDown10, ArrowDownAZ, ArrowDownAz, ArrowDownCircle, ArrowDownFromLine, ArrowDownLeft, ArrowDownLeftFromCircle, ArrowDownLeftFromSquare, ArrowDownLeftSquare, ArrowDownNarrowWide, ArrowDownRight, ArrowDownRightFromCircle, ArrowDownRightFromSquare, ArrowDownRightSquare, ArrowDownSquare, ArrowDownToDot, ArrowDownToLine, ArrowDownUp, ArrowDownWideNarrow, ArrowDownZA, ArrowDownZa, ArrowLeft, ArrowLeftCircle, ArrowLeftFromLine, ArrowLeftRight, ArrowLeftSquare, ArrowLeftToLine, ArrowRight, ArrowRightCircle, ArrowRightFromLine, ArrowRightLeft, ArrowRightSquare, ArrowRightToLine, ArrowUp, ArrowUp01, ArrowUp10, ArrowUpAZ, ArrowUpAz, ArrowUpCircle, ArrowUpDown, ArrowUpFromDot, ArrowUpFromLine, ArrowUpLeft, ArrowUpLeftFromCircle, ArrowUpLeftFromSquare, ArrowUpLeftSquare, ArrowUpNarrowWide, ArrowUpRight, ArrowUpRightFromCircle, ArrowUpRightFromSquare, ArrowUpRightSquare, ArrowUpSquare, ArrowUpToLine, ArrowUpWideNarrow, ArrowUpZA, ArrowUpZa, ArrowsUpFromLine, Asterisk, AsteriskSquare, AtSign, Atom, AudioLines, AudioWaveform, Award, Axe, Axis3D, Axis3d, Baby, Backpack, Badge, BadgeAlert, BadgeCent, BadgeCheck, BadgeDollarSign, BadgeEuro, BadgeHelp, BadgeIndianRupee, BadgeInfo, BadgeJapaneseYen, BadgeMinus, BadgePercent, BadgePlus, BadgePoundSterling, BadgeQuestionMark, BadgeRussianRuble, BadgeSwissFranc, BadgeTurkishLira, BadgeX, BaggageClaim, Balloon, Ban, Banana, Bandage, Banknote, BanknoteArrowDown, BanknoteArrowUp, BanknoteX, BarChart, BarChart2, BarChart3, BarChart4, BarChartBig, BarChartHorizontal, BarChartHorizontalBig, Barcode, Barrel, Baseline, Bath, Battery, BatteryCharging, BatteryFull, BatteryLow, BatteryMedium, BatteryPlus, BatteryWarning, Beaker, Bean, BeanOff, BedSingle, Beef, BeefOff, Beer, BeerOff, BellDot, BellElectric, BellMinus, BellOff, BellPlus, BellRing, BetweenHorizonalEnd, BetweenHorizonalStart, BetweenHorizontalEnd, BetweenHorizontalStart, BetweenVerticalEnd, BetweenVerticalStart, BicepsFlexed, Binary, Binoculars, Biohazard, Bird, Birdhouse, Bitcoin, Blend, Blinds, Blocks, Bluetooth, BluetoothConnected, BluetoothOff, BluetoothSearching, Bold, Bolt, Bomb, Bone, Book, BookA, BookAlert, BookAudio, BookCheck, BookCopy, BookDashed, BookDown, BookHeadphones, BookHeart, BookImage, BookKey, BookLock, BookMinus, BookOpenCheck, BookOpenText, BookPlus, BookSearch, BookTemplate, BookText, BookType, BookUp, BookUp2, BookUser, BookX, Bookmark, BookmarkCheck, BookmarkMinus, BookmarkOff, BookmarkPlus, BookmarkX, BoomBox, Bot, BotMessageSquare, BotOff, BottleWine, BowArrow, Box, BoxSelect, Boxes, Braces, Brackets, BrainCircuit, BrainCog, BrickWall, BrickWallFire, BrickWallShield, BriefcaseBusiness, BriefcaseConveyorBelt, BriefcaseMedical, BringToFront, BrushCleaning, Bubbles, Bug, BugOff, BugPlay, Building, Building2, Bus, BusFront, Cable, CableCar, Cake, CakeSlice, Calendar, Calendar1, CalendarArrowDown, CalendarArrowUp, CalendarCheck, CalendarCheck2, CalendarClock, CalendarCog, CalendarDays, CalendarFold, CalendarHeart, CalendarMinus, CalendarMinus2, CalendarOff, CalendarPlus, CalendarPlus2, CalendarRange, CalendarSearch, CalendarSync, CalendarX, CalendarX2, Calendars, CameraOff, CandlestickChart, Candy, CandyCane, CandyOff, Cannabis, CannabisOff, Captions, CaptionsOff, CarFront, CarTaxiFront, Caravan, CardSim, CaseLower, CaseSensitive, CaseUpper, CassetteTape, Cast, Castle, Cat, Cctv, CctvOff, ChartArea, ChartBarBig, ChartBarDecreasing, ChartBarIncreasing, ChartBarStacked, ChartCandlestick, ChartColumn, ChartColumnBig, ChartColumnDecreasing, ChartColumnIncreasing, ChartColumnStacked, ChartGantt, ChartNetwork, ChartNoAxesColumn, ChartNoAxesColumnDecreasing, ChartNoAxesColumnIncreasing, ChartNoAxesCombined, ChartNoAxesGantt, ChartPie, ChartScatter, ChartSpline, Check, CheckCheck, CheckCircle, CheckCircle2, CheckLine, CheckSquare, CheckSquare2, ChefHat, Cherry, ChessBishop, ChessKing, ChessKnight, ChessPawn, ChessQueen, ChessRook, ChevronDown, ChevronDownCircle, ChevronDownSquare, ChevronFirst, ChevronLast, ChevronLeft, ChevronLeftCircle, ChevronLeftSquare, ChevronRight, ChevronRightCircle, ChevronRightSquare, ChevronUp, ChevronUpCircle, ChevronUpSquare, ChevronsDown, ChevronsDownUp, ChevronsLeft, ChevronsLeftRight, ChevronsLeftRightEllipsis, ChevronsRight, ChevronsRightLeft, ChevronsUp, ChevronsUpDown, Church, Cigarette, CigaretteOff, Circle, CircleAlert, CircleArrowDown, CircleArrowLeft, CircleArrowOutDownLeft, CircleArrowOutDownRight, CircleArrowOutUpLeft, CircleArrowOutUpRight, CircleArrowRight, CircleArrowUp, CircleCheck, CircleCheckBig, CircleChevronDown, CircleChevronLeft, CircleChevronRight, CircleChevronUp, CircleDashed, CircleDivide, CircleDollarSign, CircleDot, CircleDotDashed, CircleEllipsis, CircleEqual, CircleFadingArrowUp, CircleFadingPlus, CircleGauge, CircleHelp, CircleMinus, CircleOff, CircleParking, CircleParkingOff, CirclePause, CirclePercent, CirclePile, CirclePlay, CirclePlus, CirclePoundSterling, CirclePower, CircleQuestionMark, CircleSlash, CircleSlash2, CircleSlashed, CircleSmall, CircleStar, CircleStop, CircleUser, CircleUserRound, CircleX, CircuitBoard, Clapperboard, Clipboard, ClipboardCheck, ClipboardClock, ClipboardCopy, ClipboardEdit, ClipboardMinus, ClipboardPaste, ClipboardPen, ClipboardPenLine, ClipboardPlus, ClipboardSignature, ClipboardType, ClipboardX, Clock, Clock1, Clock10, Clock11, Clock12, Clock2, Clock3, Clock4, Clock5, Clock6, Clock7, Clock8, Clock9, ClockAlert, ClockArrowDown, ClockArrowUp, ClockCheck, ClockFading, ClockPlus, ClosedCaption, Cloud, CloudAlert, CloudBackup, CloudCheck, CloudCog, CloudDownload, CloudDrizzle, CloudFog, CloudHail, CloudLightning, CloudMoonRain, CloudOff, CloudRain, CloudRainWind, CloudSnow, CloudSun, CloudSunRain, CloudSync, CloudUpload, Cloudy, Clover, Club
} as const;

export type HabitIconKey = keyof typeof HABIT_ICON_MAP;

// ── Metadata ─────────────────────────────────────────────────────────────

export interface IconEntry {
  key: HabitIconKey;
  label: string;
  category: string;
  tags: string[];
}

export const ICON_CATEGORIES = [
  "All",
  "Fitness",
  "Health",
  "Food",
  "Sleep",
  "Mind",
  "Finance",
  "Learning",
  "Social",
  "Productivity",
  "Lifestyle",
] as const;

export type IconCategory = (typeof ICON_CATEGORIES)[number];

export const HABIT_ICONS_LIST: IconEntry[] = [
  // ── Fitness ─────────────────────────────────────────────────────────────
  { key: "Dumbbell",        label: "Weights",     category: "Fitness",      tags: ["gym", "workout", "lift", "strength", "bodybuilding"] },
  { key: "Bike",            label: "Cycling",     category: "Fitness",      tags: ["bicycle", "cardio", "outdoor", "spin"] },
  { key: "Flame",           label: "HIIT",        category: "Fitness",      tags: ["fire", "burn", "intense", "workout"] },
  { key: "Activity",        label: "Active",      category: "Fitness",      tags: ["exercise", "pulse", "heart rate", "movement"] },
  { key: "Footprints",      label: "Walking",     category: "Fitness",      tags: ["steps", "walk", "run", "jog", "10k steps"] },
  { key: "PersonStanding",  label: "Yoga",        category: "Fitness",      tags: ["stretch", "pose", "balance", "flexibility"] },
  { key: "Weight",          label: "Weight",      category: "Fitness",      tags: ["scale", "body weight", "track", "measure"] },
  { key: "Swords",          label: "Combat",      category: "Fitness",      tags: ["martial arts", "fight", "boxing", "sparring"] },
  { key: "HeartPulse",      label: "Cardio",      category: "Fitness",      tags: ["heart rate", "pulse", "aerobic", "endurance"] },
  { key: "Timer",           label: "Timed",       category: "Fitness",      tags: ["stopwatch", "interval", "time", "plank"] },
  { key: "Zap",             label: "Sprint",      category: "Fitness",      tags: ["power", "sprint", "explosive", "fast"] },
  { key: "Wind",            label: "Breathing",   category: "Fitness",      tags: ["breath", "pranayama", "oxygen", "lung"] },
  { key: "Sun",             label: "Morning",     category: "Fitness",      tags: ["sunrise", "morning routine", "workout", "outdoor"] },
  { key: "Waves",           label: "Swimming",    category: "Fitness",      tags: ["swim", "pool", "water", "lap"] },

  // ── Health ───────────────────────────────────────────────────────────────
  { key: "Heart",           label: "Heart",       category: "Health",       tags: ["cardiovascular", "cardio", "health"] },
  { key: "Stethoscope",     label: "Doctor",      category: "Health",       tags: ["medical", "checkup", "appointment"] },
  { key: "Pill",            label: "Medicine",    category: "Health",       tags: ["medication", "supplement", "vitamins", "rx"] },
  { key: "Droplets",        label: "Hydration",   category: "Health",       tags: ["water", "drink", "fluid", "8 glasses"] },
  { key: "Eye",             label: "Vision",      category: "Health",       tags: ["eyes", "sight", "screen time", "care"] },
  { key: "Brain",           label: "Brain",       category: "Health",       tags: ["mental", "cognitive", "focus", "neuroplasticity"] },
  { key: "Thermometer",     label: "Health",      category: "Health",       tags: ["temperature", "fever", "wellness", "check"] },
  { key: "TestTube",        label: "Lab Test",    category: "Health",       tags: ["testing", "analysis", "blood", "results"] },
  { key: "Microscope",      label: "Research",    category: "Health",       tags: ["science", "detail", "analyze", "study"] },
  { key: "Syringe",         label: "Treatment",   category: "Health",       tags: ["injection", "vaccine", "medical", "shot"] },
  { key: "Dna",             label: "Genetics",    category: "Health",       tags: ["dna", "biology", "body", "genes"] },
  { key: "FlaskConical",    label: "Supplements", category: "Health",       tags: ["experiment", "chemistry", "lab", "formula"] },

  // ── Food ─────────────────────────────────────────────────────────────────
  { key: "Apple",           label: "Fruit",       category: "Food",         tags: ["healthy", "diet", "nutrition", "snack"] },
  { key: "Utensils",        label: "Meal Prep",   category: "Food",         tags: ["eat", "food", "cooking", "dinner", "lunch"] },
  { key: "Coffee",          label: "Coffee",      category: "Food",         tags: ["caffeine", "morning", "drink", "espresso"] },
  { key: "UtensilsCrossed", label: "Cooking",     category: "Food",         tags: ["kitchen", "chef", "prepare", "homemade"] },
  { key: "Pizza",           label: "Pizza",       category: "Food",         tags: ["cheat meal", "pizza", "junk food"] },
  { key: "Salad",           label: "Salad",       category: "Food",         tags: ["vegetables", "healthy", "greens", "veggies"] },
  { key: "Egg",             label: "Eggs",        category: "Food",         tags: ["protein", "breakfast", "cook", "omelette"] },
  { key: "Cookie",          label: "Treats",      category: "Food",         tags: ["sweet", "dessert", "baking", "sugar free"] },
  { key: "Sandwich",        label: "Lunch",       category: "Food",         tags: ["meal", "bread", "wrap", "midday"] },
  { key: "Wine",            label: "Alcohol",     category: "Food",         tags: ["drink", "alcohol", "social", "limit"] },
  { key: "Milk",            label: "Dairy",       category: "Food",         tags: ["calcium", "drink", "protein", "dairy free"] },
  { key: "Carrot",          label: "Vegetables",  category: "Food",         tags: ["veggie", "healthy", "orange", "plant"] },
  { key: "Wheat",           label: "Grains",      category: "Food",         tags: ["carbs", "bread", "gluten", "cereal"] },
  { key: "Citrus",          label: "Citrus",      category: "Food",         tags: ["vitamin c", "orange", "lemon", "fruit"] },
  { key: "IceCreamCone",    label: "Dessert",     category: "Food",         tags: ["sweet", "treat", "indulgence", "reward"] },

  // ── Sleep ────────────────────────────────────────────────────────────────
  { key: "Moon",            label: "Sleep",       category: "Sleep",        tags: ["night", "rest", "bed time", "8 hours"] },
  { key: "Bed",             label: "Bed",         category: "Sleep",        tags: ["rest", "sleep", "comfort", "night"] },
  { key: "BedDouble",       label: "Rest Day",    category: "Sleep",        tags: ["recover", "nap", "rest", "recharge"] },
  { key: "CloudMoon",       label: "Night",       category: "Sleep",        tags: ["night sky", "dreaming", "evening"] },
  { key: "Sunrise",         label: "Wake Up",     category: "Sleep",        tags: ["morning", "alarm", "start day", "early"] },
  { key: "Sunset",          label: "Wind Down",   category: "Sleep",        tags: ["evening", "relax", "end day", "routine"] },

  // ── Mind ─────────────────────────────────────────────────────────────────
  { key: "Smile",           label: "Mood",        category: "Mind",         tags: ["happy", "emotion", "journal", "feeling"] },
  { key: "Leaf",            label: "Nature",      category: "Mind",         tags: ["calm", "outdoors", "green", "grounding"] },
  { key: "Sprout",          label: "Growth",      category: "Mind",         tags: ["plant", "grow", "develop", "potential"] },
  { key: "Gem",             label: "Mindfulness", category: "Mind",         tags: ["crystal", "clarity", "precious", "rare"] },
  { key: "Puzzle",          label: "Challenge",   category: "Mind",         tags: ["problem solving", "brain", "logic", "strategy"] },
  { key: "Sparkle",         label: "Gratitude",   category: "Mind",         tags: ["thankful", "positive", "shine", "appreciate"] },
  { key: "HeartHandshake",  label: "Kindness",    category: "Mind",         tags: ["compassion", "help", "care", "empathy"] },
  { key: "Flower2",         label: "Peace",       category: "Mind",         tags: ["bloom", "garden", "peaceful", "calm"] },
  { key: "PawPrint",        label: "Pet Care",    category: "Mind",         tags: ["dog", "cat", "animal", "walk", "pet"] },
  { key: "Globe",           label: "Perspective", category: "Mind",         tags: ["explore", "global", "world", "open minded"] },

  // ── Finance ──────────────────────────────────────────────────────────────
  { key: "DollarSign",      label: "Money",       category: "Finance",      tags: ["income", "salary", "cash", "earn"] },
  { key: "PiggyBank",       label: "Savings",     category: "Finance",      tags: ["save", "budget", "piggy", "goal"] },
  { key: "TrendingUp",      label: "Investing",   category: "Finance",      tags: ["invest", "profit", "increase", "growth"] },
  { key: "TrendingDown",    label: "Cut Costs",   category: "Finance",      tags: ["reduce", "spending", "decrease", "less"] },
  { key: "CreditCard",      label: "Card",        category: "Finance",      tags: ["payment", "bank", "credit", "debit"] },
  { key: "Wallet",          label: "Budget",      category: "Finance",      tags: ["budget", "cash", "spending", "limit"] },
  { key: "Coins",           label: "Coins",       category: "Finance",      tags: ["change", "small savings", "spare", "coins"] },
  { key: "ChartBar",        label: "Stats",       category: "Finance",      tags: ["statistics", "data", "compare", "track"] },
  { key: "ChartLine",       label: "Progress",    category: "Finance",      tags: ["trend", "progress", "graph", "track"] },
  { key: "Landmark",        label: "Bank",        category: "Finance",      tags: ["banking", "government", "wealth", "institution"] },
  { key: "Briefcase",       label: "Business",    category: "Finance",      tags: ["work", "job", "career", "entrepreneur"] },
  { key: "Receipt",         label: "Expenses",    category: "Finance",      tags: ["bill", "track spending", "record", "log"] },

  // ── Learning ─────────────────────────────────────────────────────────────
  { key: "BookOpen",        label: "Reading",     category: "Learning",     tags: ["books", "study", "literature", "pages"] },
  { key: "GraduationCap",   label: "Education",   category: "Learning",     tags: ["school", "degree", "learn", "course"] },
  { key: "Lightbulb",       label: "Idea",        category: "Learning",     tags: ["insight", "creativity", "spark", "innovation"] },
  { key: "PenLine",         label: "Writing",     category: "Learning",     tags: ["journal", "notes", "write", "essay"] },
  { key: "Code",            label: "Coding",      category: "Learning",     tags: ["programming", "developer", "tech", "software"] },
  { key: "Library",         label: "Library",     category: "Learning",     tags: ["books", "knowledge", "resource", "reference"] },
  { key: "Telescope",       label: "Explore",     category: "Learning",     tags: ["observe", "science", "discover", "astronomy"] },
  { key: "Feather",         label: "Creative",    category: "Learning",     tags: ["writing", "poetry", "artistic", "prose"] },
  { key: "Map",             label: "Planning",    category: "Learning",     tags: ["map", "navigate", "strategy", "plan"] },
  { key: "Calculator",      label: "Math",        category: "Learning",     tags: ["numbers", "calculate", "finance", "math"] },
  { key: "Languages",       label: "Language",    category: "Learning",     tags: ["foreign", "speak", "translate", "duolingo"] },
  { key: "BookMarked",      label: "Bookmark",    category: "Learning",     tags: ["save", "reference", "note", "mark"] },
  { key: "NotebookPen",     label: "Notebook",    category: "Learning",     tags: ["journal", "diary", "notes", "log"] },

  // ── Social ───────────────────────────────────────────────────────────────
  { key: "Users",           label: "Community",   category: "Social",       tags: ["group", "team", "people", "networking"] },
  { key: "MessageCircle",   label: "Chat",        category: "Social",       tags: ["talk", "message", "connect", "dm"] },
  { key: "Phone",           label: "Call",        category: "Social",       tags: ["contact", "reach out", "talk", "call"] },
  { key: "Mail",            label: "Email",       category: "Social",       tags: ["message", "contact", "inbox", "send"] },
  { key: "Video",           label: "Video Call",  category: "Social",       tags: ["zoom", "meet", "virtual", "hang out"] },
  { key: "UserPlus",        label: "Network",     category: "Social",       tags: ["connect", "friend", "add", "new people"] },
  { key: "Share2",          label: "Share",       category: "Social",       tags: ["spread", "post", "publish", "social media"] },
  { key: "Handshake",       label: "Agreement",   category: "Social",       tags: ["deal", "partner", "trust", "collaboration"] },
  { key: "PartyPopper",     label: "Celebrate",   category: "Social",       tags: ["celebration", "fun", "event", "milestone"] },

  // ── Productivity ──────────────────────────────────────────────────────────
  { key: "Target",          label: "Goal",        category: "Productivity", tags: ["aim", "objective", "focus", "target"] },
  { key: "Trophy",          label: "Achievement", category: "Productivity", tags: ["win", "success", "award", "milestone"] },
  { key: "Star",            label: "Priority",    category: "Productivity", tags: ["important", "favorite", "highlight", "top"] },
  { key: "Rocket",          label: "Launch",      category: "Productivity", tags: ["startup", "boost", "growth", "accelerate"] },
  { key: "SquareCheck",     label: "Done",        category: "Productivity", tags: ["complete", "tick", "finished", "check"] },
  { key: "ClipboardList",   label: "Checklist",   category: "Productivity", tags: ["tasks", "todo", "list", "items"] },
  { key: "Flag",            label: "Milestone",   category: "Productivity", tags: ["mark", "event", "complete", "checkpoint"] },
  { key: "Bell",            label: "Reminder",    category: "Productivity", tags: ["alert", "notify", "schedule", "ping"] },
  { key: "AlarmClock",      label: "Alarm",       category: "Productivity", tags: ["wake up", "reminder", "time", "alarm"] },
  { key: "Gauge",           label: "Performance", category: "Productivity", tags: ["speed", "meter", "performance", "kpi"] },
  { key: "ListTodo",        label: "To-Do",       category: "Productivity", tags: ["tasks", "list", "check", "agenda"] },
  { key: "LayoutDashboard", label: "Dashboard",   category: "Productivity", tags: ["overview", "track", "organize", "control"] },
  { key: "Kanban",          label: "Kanban",      category: "Productivity", tags: ["board", "tasks", "workflow", "agile"] },

  // ── Lifestyle ────────────────────────────────────────────────────────────
  { key: "Music",           label: "Music",       category: "Lifestyle",    tags: ["listen", "practice", "playlist", "instrument"] },
  { key: "Camera",          label: "Photography", category: "Lifestyle",    tags: ["photo", "shoot", "capture", "pictures"] },
  { key: "Home",            label: "Home",        category: "Lifestyle",    tags: ["house", "chores", "clean", "tidy"] },
  { key: "ShoppingCart",    label: "Groceries",   category: "Lifestyle",    tags: ["buy", "groceries", "errands", "shop"] },
  { key: "Smartphone",      label: "Digital",     category: "Lifestyle",    tags: ["phone", "screen time", "app", "limit"] },
  { key: "Gamepad2",        label: "Gaming",      category: "Lifestyle",    tags: ["play", "games", "relax", "entertainment"] },
  { key: "Headphones",      label: "Podcast",     category: "Lifestyle",    tags: ["listen", "audio", "podcast", "audiobook"] },
  { key: "Tv",              label: "TV",          category: "Lifestyle",    tags: ["watch", "screen", "media", "streaming"] },
  { key: "Car",             label: "Driving",     category: "Lifestyle",    tags: ["commute", "transport", "drive", "car"] },
  { key: "Plane",           label: "Travel",      category: "Lifestyle",    tags: ["trip", "vacation", "fly", "adventure"] },
  { key: "Scissors",        label: "Crafts",      category: "Lifestyle",    tags: ["create", "diy", "make", "craft"] },
  { key: "Brush",           label: "Art",         category: "Lifestyle",    tags: ["paint", "creative", "draw", "artist"] },
  { key: "Palette",         label: "Design",      category: "Lifestyle",    tags: ["color", "creative", "art", "visual"] },
  { key: "Shirt",           label: "Fashion",     category: "Lifestyle",    tags: ["clothes", "style", "dress", "wardrobe"] },
  { key: "Watch",           label: "Time",        category: "Lifestyle",    tags: ["schedule", "punctual", "track", "manage"] },
  { key: "Trees",           label: "Nature Walk", category: "Lifestyle",    tags: ["outdoors", "forest", "hiking", "green"] },
  { key: "Mountain",        label: "Hiking",      category: "Lifestyle",    tags: ["climb", "outdoor", "adventure", "peak"] },
  // ── 500 Additional Icons ──────────────────────────────────────────────────
  { key: "AArrowDown", label: "A Arrow Down", category: "All", tags: [] },
  { key: "AArrowUp", label: "A Arrow Up", category: "All", tags: [] },
  { key: "ALargeSmall", label: "A Large Small", category: "All", tags: [] },
  { key: "Accessibility", label: "Accessibility", category: "All", tags: [] },
  { key: "ActivitySquare", label: "Activity Square", category: "All", tags: [] },
  { key: "AirVent", label: "Air Vent", category: "All", tags: [] },
  { key: "Airplay", label: "Airplay", category: "All", tags: [] },
  { key: "AlarmCheck", label: "Alarm Check", category: "All", tags: [] },
  { key: "AlarmClockCheck", label: "Alarm Clock Check", category: "All", tags: [] },
  { key: "AlarmClockMinus", label: "Alarm Clock Minus", category: "All", tags: [] },
  { key: "AlarmClockOff", label: "Alarm Clock Off", category: "All", tags: [] },
  { key: "AlarmClockPlus", label: "Alarm Clock Plus", category: "All", tags: [] },
  { key: "AlarmMinus", label: "Alarm Minus", category: "All", tags: [] },
  { key: "AlarmPlus", label: "Alarm Plus", category: "All", tags: [] },
  { key: "AlarmSmoke", label: "Alarm Smoke", category: "All", tags: [] },
  { key: "Album", label: "Album", category: "All", tags: [] },
  { key: "AlertCircle", label: "Alert Circle", category: "All", tags: [] },
  { key: "AlertOctagon", label: "Alert Octagon", category: "All", tags: [] },
  { key: "AlertTriangle", label: "Alert Triangle", category: "All", tags: [] },
  { key: "AlignCenter", label: "Align Center", category: "All", tags: [] },
  { key: "AlignCenterHorizontal", label: "Align Center Horizontal", category: "All", tags: [] },
  { key: "AlignCenterVertical", label: "Align Center Vertical", category: "All", tags: [] },
  { key: "AlignEndHorizontal", label: "Align End Horizontal", category: "All", tags: [] },
  { key: "AlignEndVertical", label: "Align End Vertical", category: "All", tags: [] },
  { key: "AlignHorizontalDistributeCenter", label: "Align Horizontal Distribute Center", category: "All", tags: [] },
  { key: "AlignHorizontalDistributeEnd", label: "Align Horizontal Distribute End", category: "All", tags: [] },
  { key: "AlignHorizontalDistributeStart", label: "Align Horizontal Distribute Start", category: "All", tags: [] },
  { key: "AlignHorizontalJustifyCenter", label: "Align Horizontal Justify Center", category: "All", tags: [] },
  { key: "AlignHorizontalJustifyEnd", label: "Align Horizontal Justify End", category: "All", tags: [] },
  { key: "AlignHorizontalJustifyStart", label: "Align Horizontal Justify Start", category: "All", tags: [] },
  { key: "AlignHorizontalSpaceAround", label: "Align Horizontal Space Around", category: "All", tags: [] },
  { key: "AlignHorizontalSpaceBetween", label: "Align Horizontal Space Between", category: "All", tags: [] },
  { key: "AlignJustify", label: "Align Justify", category: "All", tags: [] },
  { key: "AlignLeft", label: "Align Left", category: "All", tags: [] },
  { key: "AlignRight", label: "Align Right", category: "All", tags: [] },
  { key: "AlignStartHorizontal", label: "Align Start Horizontal", category: "All", tags: [] },
  { key: "AlignStartVertical", label: "Align Start Vertical", category: "All", tags: [] },
  { key: "AlignVerticalDistributeCenter", label: "Align Vertical Distribute Center", category: "All", tags: [] },
  { key: "AlignVerticalDistributeEnd", label: "Align Vertical Distribute End", category: "All", tags: [] },
  { key: "AlignVerticalDistributeStart", label: "Align Vertical Distribute Start", category: "All", tags: [] },
  { key: "AlignVerticalJustifyCenter", label: "Align Vertical Justify Center", category: "All", tags: [] },
  { key: "AlignVerticalJustifyEnd", label: "Align Vertical Justify End", category: "All", tags: [] },
  { key: "AlignVerticalJustifyStart", label: "Align Vertical Justify Start", category: "All", tags: [] },
  { key: "AlignVerticalSpaceAround", label: "Align Vertical Space Around", category: "All", tags: [] },
  { key: "AlignVerticalSpaceBetween", label: "Align Vertical Space Between", category: "All", tags: [] },
  { key: "Ambulance", label: "Ambulance", category: "All", tags: [] },
  { key: "Ampersand", label: "Ampersand", category: "All", tags: [] },
  { key: "Ampersands", label: "Ampersands", category: "All", tags: [] },
  { key: "Amphora", label: "Amphora", category: "All", tags: [] },
  { key: "Anchor", label: "Anchor", category: "All", tags: [] },
  { key: "Angry", label: "Angry", category: "All", tags: [] },
  { key: "Annoyed", label: "Annoyed", category: "All", tags: [] },
  { key: "Antenna", label: "Antenna", category: "All", tags: [] },
  { key: "Anvil", label: "Anvil", category: "All", tags: [] },
  { key: "Aperture", label: "Aperture", category: "All", tags: [] },
  { key: "AppWindow", label: "App Window", category: "All", tags: [] },
  { key: "AppWindowMac", label: "App Window Mac", category: "All", tags: [] },
  { key: "Archive", label: "Archive", category: "All", tags: [] },
  { key: "ArchiveRestore", label: "Archive Restore", category: "All", tags: [] },
  { key: "ArchiveX", label: "Archive X", category: "All", tags: [] },
  { key: "AreaChart", label: "Area Chart", category: "All", tags: [] },
  { key: "Armchair", label: "Armchair", category: "All", tags: [] },
  { key: "ArrowBigDown", label: "Arrow Big Down", category: "All", tags: [] },
  { key: "ArrowBigDownDash", label: "Arrow Big Down Dash", category: "All", tags: [] },
  { key: "ArrowBigLeft", label: "Arrow Big Left", category: "All", tags: [] },
  { key: "ArrowBigLeftDash", label: "Arrow Big Left Dash", category: "All", tags: [] },
  { key: "ArrowBigRight", label: "Arrow Big Right", category: "All", tags: [] },
  { key: "ArrowBigRightDash", label: "Arrow Big Right Dash", category: "All", tags: [] },
  { key: "ArrowBigUp", label: "Arrow Big Up", category: "All", tags: [] },
  { key: "ArrowBigUpDash", label: "Arrow Big Up Dash", category: "All", tags: [] },
  { key: "ArrowDown", label: "Arrow Down", category: "All", tags: [] },
  { key: "ArrowDown01", label: "Arrow Down01", category: "All", tags: [] },
  { key: "ArrowDown10", label: "Arrow Down10", category: "All", tags: [] },
  { key: "ArrowDownAZ", label: "Arrow Down A Z", category: "All", tags: [] },
  { key: "ArrowDownAz", label: "Arrow Down Az", category: "All", tags: [] },
  { key: "ArrowDownCircle", label: "Arrow Down Circle", category: "All", tags: [] },
  { key: "ArrowDownFromLine", label: "Arrow Down From Line", category: "All", tags: [] },
  { key: "ArrowDownLeft", label: "Arrow Down Left", category: "All", tags: [] },
  { key: "ArrowDownLeftFromCircle", label: "Arrow Down Left From Circle", category: "All", tags: [] },
  { key: "ArrowDownLeftFromSquare", label: "Arrow Down Left From Square", category: "All", tags: [] },
  { key: "ArrowDownLeftSquare", label: "Arrow Down Left Square", category: "All", tags: [] },
  { key: "ArrowDownNarrowWide", label: "Arrow Down Narrow Wide", category: "All", tags: [] },
  { key: "ArrowDownRight", label: "Arrow Down Right", category: "All", tags: [] },
  { key: "ArrowDownRightFromCircle", label: "Arrow Down Right From Circle", category: "All", tags: [] },
  { key: "ArrowDownRightFromSquare", label: "Arrow Down Right From Square", category: "All", tags: [] },
  { key: "ArrowDownRightSquare", label: "Arrow Down Right Square", category: "All", tags: [] },
  { key: "ArrowDownSquare", label: "Arrow Down Square", category: "All", tags: [] },
  { key: "ArrowDownToDot", label: "Arrow Down To Dot", category: "All", tags: [] },
  { key: "ArrowDownToLine", label: "Arrow Down To Line", category: "All", tags: [] },
  { key: "ArrowDownUp", label: "Arrow Down Up", category: "All", tags: [] },
  { key: "ArrowDownWideNarrow", label: "Arrow Down Wide Narrow", category: "All", tags: [] },
  { key: "ArrowDownZA", label: "Arrow Down Z A", category: "All", tags: [] },
  { key: "ArrowDownZa", label: "Arrow Down Za", category: "All", tags: [] },
  { key: "ArrowLeft", label: "Arrow Left", category: "All", tags: [] },
  { key: "ArrowLeftCircle", label: "Arrow Left Circle", category: "All", tags: [] },
  { key: "ArrowLeftFromLine", label: "Arrow Left From Line", category: "All", tags: [] },
  { key: "ArrowLeftRight", label: "Arrow Left Right", category: "All", tags: [] },
  { key: "ArrowLeftSquare", label: "Arrow Left Square", category: "All", tags: [] },
  { key: "ArrowLeftToLine", label: "Arrow Left To Line", category: "All", tags: [] },
  { key: "ArrowRight", label: "Arrow Right", category: "All", tags: [] },
  { key: "ArrowRightCircle", label: "Arrow Right Circle", category: "All", tags: [] },
  { key: "ArrowRightFromLine", label: "Arrow Right From Line", category: "All", tags: [] },
  { key: "ArrowRightLeft", label: "Arrow Right Left", category: "All", tags: [] },
  { key: "ArrowRightSquare", label: "Arrow Right Square", category: "All", tags: [] },
  { key: "ArrowRightToLine", label: "Arrow Right To Line", category: "All", tags: [] },
  { key: "ArrowUp", label: "Arrow Up", category: "All", tags: [] },
  { key: "ArrowUp01", label: "Arrow Up01", category: "All", tags: [] },
  { key: "ArrowUp10", label: "Arrow Up10", category: "All", tags: [] },
  { key: "ArrowUpAZ", label: "Arrow Up A Z", category: "All", tags: [] },
  { key: "ArrowUpAz", label: "Arrow Up Az", category: "All", tags: [] },
  { key: "ArrowUpCircle", label: "Arrow Up Circle", category: "All", tags: [] },
  { key: "ArrowUpDown", label: "Arrow Up Down", category: "All", tags: [] },
  { key: "ArrowUpFromDot", label: "Arrow Up From Dot", category: "All", tags: [] },
  { key: "ArrowUpFromLine", label: "Arrow Up From Line", category: "All", tags: [] },
  { key: "ArrowUpLeft", label: "Arrow Up Left", category: "All", tags: [] },
  { key: "ArrowUpLeftFromCircle", label: "Arrow Up Left From Circle", category: "All", tags: [] },
  { key: "ArrowUpLeftFromSquare", label: "Arrow Up Left From Square", category: "All", tags: [] },
  { key: "ArrowUpLeftSquare", label: "Arrow Up Left Square", category: "All", tags: [] },
  { key: "ArrowUpNarrowWide", label: "Arrow Up Narrow Wide", category: "All", tags: [] },
  { key: "ArrowUpRight", label: "Arrow Up Right", category: "All", tags: [] },
  { key: "ArrowUpRightFromCircle", label: "Arrow Up Right From Circle", category: "All", tags: [] },
  { key: "ArrowUpRightFromSquare", label: "Arrow Up Right From Square", category: "All", tags: [] },
  { key: "ArrowUpRightSquare", label: "Arrow Up Right Square", category: "All", tags: [] },
  { key: "ArrowUpSquare", label: "Arrow Up Square", category: "All", tags: [] },
  { key: "ArrowUpToLine", label: "Arrow Up To Line", category: "All", tags: [] },
  { key: "ArrowUpWideNarrow", label: "Arrow Up Wide Narrow", category: "All", tags: [] },
  { key: "ArrowUpZA", label: "Arrow Up Z A", category: "All", tags: [] },
  { key: "ArrowUpZa", label: "Arrow Up Za", category: "All", tags: [] },
  { key: "ArrowsUpFromLine", label: "Arrows Up From Line", category: "All", tags: [] },
  { key: "Asterisk", label: "Asterisk", category: "All", tags: [] },
  { key: "AsteriskSquare", label: "Asterisk Square", category: "All", tags: [] },
  { key: "AtSign", label: "At Sign", category: "All", tags: [] },
  { key: "Atom", label: "Atom", category: "All", tags: [] },
  { key: "AudioLines", label: "Audio Lines", category: "All", tags: [] },
  { key: "AudioWaveform", label: "Audio Waveform", category: "All", tags: [] },
  { key: "Award", label: "Award", category: "All", tags: [] },
  { key: "Axe", label: "Axe", category: "All", tags: [] },
  { key: "Axis3D", label: "Axis3 D", category: "All", tags: [] },
  { key: "Axis3d", label: "Axis3d", category: "All", tags: [] },
  { key: "Baby", label: "Baby", category: "All", tags: [] },
  { key: "Backpack", label: "Backpack", category: "All", tags: [] },
  { key: "Badge", label: "Badge", category: "All", tags: [] },
  { key: "BadgeAlert", label: "Badge Alert", category: "All", tags: [] },
  { key: "BadgeCent", label: "Badge Cent", category: "All", tags: [] },
  { key: "BadgeCheck", label: "Badge Check", category: "All", tags: [] },
  { key: "BadgeDollarSign", label: "Badge Dollar Sign", category: "All", tags: [] },
  { key: "BadgeEuro", label: "Badge Euro", category: "All", tags: [] },
  { key: "BadgeHelp", label: "Badge Help", category: "All", tags: [] },
  { key: "BadgeIndianRupee", label: "Badge Indian Rupee", category: "All", tags: [] },
  { key: "BadgeInfo", label: "Badge Info", category: "All", tags: [] },
  { key: "BadgeJapaneseYen", label: "Badge Japanese Yen", category: "All", tags: [] },
  { key: "BadgeMinus", label: "Badge Minus", category: "All", tags: [] },
  { key: "BadgePercent", label: "Badge Percent", category: "All", tags: [] },
  { key: "BadgePlus", label: "Badge Plus", category: "All", tags: [] },
  { key: "BadgePoundSterling", label: "Badge Pound Sterling", category: "All", tags: [] },
  { key: "BadgeQuestionMark", label: "Badge Question Mark", category: "All", tags: [] },
  { key: "BadgeRussianRuble", label: "Badge Russian Ruble", category: "All", tags: [] },
  { key: "BadgeSwissFranc", label: "Badge Swiss Franc", category: "All", tags: [] },
  { key: "BadgeTurkishLira", label: "Badge Turkish Lira", category: "All", tags: [] },
  { key: "BadgeX", label: "Badge X", category: "All", tags: [] },
  { key: "BaggageClaim", label: "Baggage Claim", category: "All", tags: [] },
  { key: "Balloon", label: "Balloon", category: "All", tags: [] },
  { key: "Ban", label: "Ban", category: "All", tags: [] },
  { key: "Banana", label: "Banana", category: "All", tags: [] },
  { key: "Bandage", label: "Bandage", category: "All", tags: [] },
  { key: "Banknote", label: "Banknote", category: "All", tags: [] },
  { key: "BanknoteArrowDown", label: "Banknote Arrow Down", category: "All", tags: [] },
  { key: "BanknoteArrowUp", label: "Banknote Arrow Up", category: "All", tags: [] },
  { key: "BanknoteX", label: "Banknote X", category: "All", tags: [] },
  { key: "BarChart", label: "Bar Chart", category: "All", tags: [] },
  { key: "BarChart2", label: "Bar Chart2", category: "All", tags: [] },
  { key: "BarChart3", label: "Bar Chart3", category: "All", tags: [] },
  { key: "BarChart4", label: "Bar Chart4", category: "All", tags: [] },
  { key: "BarChartBig", label: "Bar Chart Big", category: "All", tags: [] },
  { key: "BarChartHorizontal", label: "Bar Chart Horizontal", category: "All", tags: [] },
  { key: "BarChartHorizontalBig", label: "Bar Chart Horizontal Big", category: "All", tags: [] },
  { key: "Barcode", label: "Barcode", category: "All", tags: [] },
  { key: "Barrel", label: "Barrel", category: "All", tags: [] },
  { key: "Baseline", label: "Baseline", category: "All", tags: [] },
  { key: "Bath", label: "Bath", category: "All", tags: [] },
  { key: "Battery", label: "Battery", category: "All", tags: [] },
  { key: "BatteryCharging", label: "Battery Charging", category: "All", tags: [] },
  { key: "BatteryFull", label: "Battery Full", category: "All", tags: [] },
  { key: "BatteryLow", label: "Battery Low", category: "All", tags: [] },
  { key: "BatteryMedium", label: "Battery Medium", category: "All", tags: [] },
  { key: "BatteryPlus", label: "Battery Plus", category: "All", tags: [] },
  { key: "BatteryWarning", label: "Battery Warning", category: "All", tags: [] },
  { key: "Beaker", label: "Beaker", category: "All", tags: [] },
  { key: "Bean", label: "Bean", category: "All", tags: [] },
  { key: "BeanOff", label: "Bean Off", category: "All", tags: [] },
  { key: "BedSingle", label: "Bed Single", category: "All", tags: [] },
  { key: "Beef", label: "Beef", category: "All", tags: [] },
  { key: "BeefOff", label: "Beef Off", category: "All", tags: [] },
  { key: "Beer", label: "Beer", category: "All", tags: [] },
  { key: "BeerOff", label: "Beer Off", category: "All", tags: [] },
  { key: "BellDot", label: "Bell Dot", category: "All", tags: [] },
  { key: "BellElectric", label: "Bell Electric", category: "All", tags: [] },
  { key: "BellMinus", label: "Bell Minus", category: "All", tags: [] },
  { key: "BellOff", label: "Bell Off", category: "All", tags: [] },
  { key: "BellPlus", label: "Bell Plus", category: "All", tags: [] },
  { key: "BellRing", label: "Bell Ring", category: "All", tags: [] },
  { key: "BetweenHorizonalEnd", label: "Between Horizonal End", category: "All", tags: [] },
  { key: "BetweenHorizonalStart", label: "Between Horizonal Start", category: "All", tags: [] },
  { key: "BetweenHorizontalEnd", label: "Between Horizontal End", category: "All", tags: [] },
  { key: "BetweenHorizontalStart", label: "Between Horizontal Start", category: "All", tags: [] },
  { key: "BetweenVerticalEnd", label: "Between Vertical End", category: "All", tags: [] },
  { key: "BetweenVerticalStart", label: "Between Vertical Start", category: "All", tags: [] },
  { key: "BicepsFlexed", label: "Biceps Flexed", category: "All", tags: [] },
  { key: "Binary", label: "Binary", category: "All", tags: [] },
  { key: "Binoculars", label: "Binoculars", category: "All", tags: [] },
  { key: "Biohazard", label: "Biohazard", category: "All", tags: [] },
  { key: "Bird", label: "Bird", category: "All", tags: [] },
  { key: "Birdhouse", label: "Birdhouse", category: "All", tags: [] },
  { key: "Bitcoin", label: "Bitcoin", category: "All", tags: [] },
  { key: "Blend", label: "Blend", category: "All", tags: [] },
  { key: "Blinds", label: "Blinds", category: "All", tags: [] },
  { key: "Blocks", label: "Blocks", category: "All", tags: [] },
  { key: "Bluetooth", label: "Bluetooth", category: "All", tags: [] },
  { key: "BluetoothConnected", label: "Bluetooth Connected", category: "All", tags: [] },
  { key: "BluetoothOff", label: "Bluetooth Off", category: "All", tags: [] },
  { key: "BluetoothSearching", label: "Bluetooth Searching", category: "All", tags: [] },
  { key: "Bold", label: "Bold", category: "All", tags: [] },
  { key: "Bolt", label: "Bolt", category: "All", tags: [] },
  { key: "Bomb", label: "Bomb", category: "All", tags: [] },
  { key: "Bone", label: "Bone", category: "All", tags: [] },
  { key: "Book", label: "Book", category: "All", tags: [] },
  { key: "BookA", label: "Book A", category: "All", tags: [] },
  { key: "BookAlert", label: "Book Alert", category: "All", tags: [] },
  { key: "BookAudio", label: "Book Audio", category: "All", tags: [] },
  { key: "BookCheck", label: "Book Check", category: "All", tags: [] },
  { key: "BookCopy", label: "Book Copy", category: "All", tags: [] },
  { key: "BookDashed", label: "Book Dashed", category: "All", tags: [] },
  { key: "BookDown", label: "Book Down", category: "All", tags: [] },
  { key: "BookHeadphones", label: "Book Headphones", category: "All", tags: [] },
  { key: "BookHeart", label: "Book Heart", category: "All", tags: [] },
  { key: "BookImage", label: "Book Image", category: "All", tags: [] },
  { key: "BookKey", label: "Book Key", category: "All", tags: [] },
  { key: "BookLock", label: "Book Lock", category: "All", tags: [] },
  { key: "BookMinus", label: "Book Minus", category: "All", tags: [] },
  { key: "BookOpenCheck", label: "Book Open Check", category: "All", tags: [] },
  { key: "BookOpenText", label: "Book Open Text", category: "All", tags: [] },
  { key: "BookPlus", label: "Book Plus", category: "All", tags: [] },
  { key: "BookSearch", label: "Book Search", category: "All", tags: [] },
  { key: "BookTemplate", label: "Book Template", category: "All", tags: [] },
  { key: "BookText", label: "Book Text", category: "All", tags: [] },
  { key: "BookType", label: "Book Type", category: "All", tags: [] },
  { key: "BookUp", label: "Book Up", category: "All", tags: [] },
  { key: "BookUp2", label: "Book Up2", category: "All", tags: [] },
  { key: "BookUser", label: "Book User", category: "All", tags: [] },
  { key: "BookX", label: "Book X", category: "All", tags: [] },
  { key: "Bookmark", label: "Bookmark", category: "All", tags: [] },
  { key: "BookmarkCheck", label: "Bookmark Check", category: "All", tags: [] },
  { key: "BookmarkMinus", label: "Bookmark Minus", category: "All", tags: [] },
  { key: "BookmarkOff", label: "Bookmark Off", category: "All", tags: [] },
  { key: "BookmarkPlus", label: "Bookmark Plus", category: "All", tags: [] },
  { key: "BookmarkX", label: "Bookmark X", category: "All", tags: [] },
  { key: "BoomBox", label: "Boom Box", category: "All", tags: [] },
  { key: "Bot", label: "Bot", category: "All", tags: [] },
  { key: "BotMessageSquare", label: "Bot Message Square", category: "All", tags: [] },
  { key: "BotOff", label: "Bot Off", category: "All", tags: [] },
  { key: "BottleWine", label: "Bottle Wine", category: "All", tags: [] },
  { key: "BowArrow", label: "Bow Arrow", category: "All", tags: [] },
  { key: "Box", label: "Box", category: "All", tags: [] },
  { key: "BoxSelect", label: "Box Select", category: "All", tags: [] },
  { key: "Boxes", label: "Boxes", category: "All", tags: [] },
  { key: "Braces", label: "Braces", category: "All", tags: [] },
  { key: "Brackets", label: "Brackets", category: "All", tags: [] },
  { key: "BrainCircuit", label: "Brain Circuit", category: "All", tags: [] },
  { key: "BrainCog", label: "Brain Cog", category: "All", tags: [] },
  { key: "BrickWall", label: "Brick Wall", category: "All", tags: [] },
  { key: "BrickWallFire", label: "Brick Wall Fire", category: "All", tags: [] },
  { key: "BrickWallShield", label: "Brick Wall Shield", category: "All", tags: [] },
  { key: "BriefcaseBusiness", label: "Briefcase Business", category: "All", tags: [] },
  { key: "BriefcaseConveyorBelt", label: "Briefcase Conveyor Belt", category: "All", tags: [] },
  { key: "BriefcaseMedical", label: "Briefcase Medical", category: "All", tags: [] },
  { key: "BringToFront", label: "Bring To Front", category: "All", tags: [] },
  { key: "BrushCleaning", label: "Brush Cleaning", category: "All", tags: [] },
  { key: "Bubbles", label: "Bubbles", category: "All", tags: [] },
  { key: "Bug", label: "Bug", category: "All", tags: [] },
  { key: "BugOff", label: "Bug Off", category: "All", tags: [] },
  { key: "BugPlay", label: "Bug Play", category: "All", tags: [] },
  { key: "Building", label: "Building", category: "All", tags: [] },
  { key: "Building2", label: "Building2", category: "All", tags: [] },
  { key: "Bus", label: "Bus", category: "All", tags: [] },
  { key: "BusFront", label: "Bus Front", category: "All", tags: [] },
  { key: "Cable", label: "Cable", category: "All", tags: [] },
  { key: "CableCar", label: "Cable Car", category: "All", tags: [] },
  { key: "Cake", label: "Cake", category: "All", tags: [] },
  { key: "CakeSlice", label: "Cake Slice", category: "All", tags: [] },
  { key: "Calendar", label: "Calendar", category: "All", tags: [] },
  { key: "Calendar1", label: "Calendar1", category: "All", tags: [] },
  { key: "CalendarArrowDown", label: "Calendar Arrow Down", category: "All", tags: [] },
  { key: "CalendarArrowUp", label: "Calendar Arrow Up", category: "All", tags: [] },
  { key: "CalendarCheck", label: "Calendar Check", category: "All", tags: [] },
  { key: "CalendarCheck2", label: "Calendar Check2", category: "All", tags: [] },
  { key: "CalendarClock", label: "Calendar Clock", category: "All", tags: [] },
  { key: "CalendarCog", label: "Calendar Cog", category: "All", tags: [] },
  { key: "CalendarDays", label: "Calendar Days", category: "All", tags: [] },
  { key: "CalendarFold", label: "Calendar Fold", category: "All", tags: [] },
  { key: "CalendarHeart", label: "Calendar Heart", category: "All", tags: [] },
  { key: "CalendarMinus", label: "Calendar Minus", category: "All", tags: [] },
  { key: "CalendarMinus2", label: "Calendar Minus2", category: "All", tags: [] },
  { key: "CalendarOff", label: "Calendar Off", category: "All", tags: [] },
  { key: "CalendarPlus", label: "Calendar Plus", category: "All", tags: [] },
  { key: "CalendarPlus2", label: "Calendar Plus2", category: "All", tags: [] },
  { key: "CalendarRange", label: "Calendar Range", category: "All", tags: [] },
  { key: "CalendarSearch", label: "Calendar Search", category: "All", tags: [] },
  { key: "CalendarSync", label: "Calendar Sync", category: "All", tags: [] },
  { key: "CalendarX", label: "Calendar X", category: "All", tags: [] },
  { key: "CalendarX2", label: "Calendar X2", category: "All", tags: [] },
  { key: "Calendars", label: "Calendars", category: "All", tags: [] },
  { key: "CameraOff", label: "Camera Off", category: "All", tags: [] },
  { key: "CandlestickChart", label: "Candlestick Chart", category: "All", tags: [] },
  { key: "Candy", label: "Candy", category: "All", tags: [] },
  { key: "CandyCane", label: "Candy Cane", category: "All", tags: [] },
  { key: "CandyOff", label: "Candy Off", category: "All", tags: [] },
  { key: "Cannabis", label: "Cannabis", category: "All", tags: [] },
  { key: "CannabisOff", label: "Cannabis Off", category: "All", tags: [] },
  { key: "Captions", label: "Captions", category: "All", tags: [] },
  { key: "CaptionsOff", label: "Captions Off", category: "All", tags: [] },
  { key: "CarFront", label: "Car Front", category: "All", tags: [] },
  { key: "CarTaxiFront", label: "Car Taxi Front", category: "All", tags: [] },
  { key: "Caravan", label: "Caravan", category: "All", tags: [] },
  { key: "CardSim", label: "Card Sim", category: "All", tags: [] },
  { key: "CaseLower", label: "Case Lower", category: "All", tags: [] },
  { key: "CaseSensitive", label: "Case Sensitive", category: "All", tags: [] },
  { key: "CaseUpper", label: "Case Upper", category: "All", tags: [] },
  { key: "CassetteTape", label: "Cassette Tape", category: "All", tags: [] },
  { key: "Cast", label: "Cast", category: "All", tags: [] },
  { key: "Castle", label: "Castle", category: "All", tags: [] },
  { key: "Cat", label: "Cat", category: "All", tags: [] },
  { key: "Cctv", label: "Cctv", category: "All", tags: [] },
  { key: "CctvOff", label: "Cctv Off", category: "All", tags: [] },
  { key: "ChartArea", label: "Chart Area", category: "All", tags: [] },
  { key: "ChartBarBig", label: "Chart Bar Big", category: "All", tags: [] },
  { key: "ChartBarDecreasing", label: "Chart Bar Decreasing", category: "All", tags: [] },
  { key: "ChartBarIncreasing", label: "Chart Bar Increasing", category: "All", tags: [] },
  { key: "ChartBarStacked", label: "Chart Bar Stacked", category: "All", tags: [] },
  { key: "ChartCandlestick", label: "Chart Candlestick", category: "All", tags: [] },
  { key: "ChartColumn", label: "Chart Column", category: "All", tags: [] },
  { key: "ChartColumnBig", label: "Chart Column Big", category: "All", tags: [] },
  { key: "ChartColumnDecreasing", label: "Chart Column Decreasing", category: "All", tags: [] },
  { key: "ChartColumnIncreasing", label: "Chart Column Increasing", category: "All", tags: [] },
  { key: "ChartColumnStacked", label: "Chart Column Stacked", category: "All", tags: [] },
  { key: "ChartGantt", label: "Chart Gantt", category: "All", tags: [] },
  { key: "ChartNetwork", label: "Chart Network", category: "All", tags: [] },
  { key: "ChartNoAxesColumn", label: "Chart No Axes Column", category: "All", tags: [] },
  { key: "ChartNoAxesColumnDecreasing", label: "Chart No Axes Column Decreasing", category: "All", tags: [] },
  { key: "ChartNoAxesColumnIncreasing", label: "Chart No Axes Column Increasing", category: "All", tags: [] },
  { key: "ChartNoAxesCombined", label: "Chart No Axes Combined", category: "All", tags: [] },
  { key: "ChartNoAxesGantt", label: "Chart No Axes Gantt", category: "All", tags: [] },
  { key: "ChartPie", label: "Chart Pie", category: "All", tags: [] },
  { key: "ChartScatter", label: "Chart Scatter", category: "All", tags: [] },
  { key: "ChartSpline", label: "Chart Spline", category: "All", tags: [] },
  { key: "Check", label: "Check", category: "All", tags: [] },
  { key: "CheckCheck", label: "Check Check", category: "All", tags: [] },
  { key: "CheckCircle", label: "Check Circle", category: "All", tags: [] },
  { key: "CheckCircle2", label: "Check Circle2", category: "All", tags: [] },
  { key: "CheckLine", label: "Check Line", category: "All", tags: [] },
  { key: "CheckSquare", label: "Check Square", category: "All", tags: [] },
  { key: "CheckSquare2", label: "Check Square2", category: "All", tags: [] },
  { key: "ChefHat", label: "Chef Hat", category: "All", tags: [] },
  { key: "Cherry", label: "Cherry", category: "All", tags: [] },
  { key: "ChessBishop", label: "Chess Bishop", category: "All", tags: [] },
  { key: "ChessKing", label: "Chess King", category: "All", tags: [] },
  { key: "ChessKnight", label: "Chess Knight", category: "All", tags: [] },
  { key: "ChessPawn", label: "Chess Pawn", category: "All", tags: [] },
  { key: "ChessQueen", label: "Chess Queen", category: "All", tags: [] },
  { key: "ChessRook", label: "Chess Rook", category: "All", tags: [] },
  { key: "ChevronDown", label: "Chevron Down", category: "All", tags: [] },
  { key: "ChevronDownCircle", label: "Chevron Down Circle", category: "All", tags: [] },
  { key: "ChevronDownSquare", label: "Chevron Down Square", category: "All", tags: [] },
  { key: "ChevronFirst", label: "Chevron First", category: "All", tags: [] },
  { key: "ChevronLast", label: "Chevron Last", category: "All", tags: [] },
  { key: "ChevronLeft", label: "Chevron Left", category: "All", tags: [] },
  { key: "ChevronLeftCircle", label: "Chevron Left Circle", category: "All", tags: [] },
  { key: "ChevronLeftSquare", label: "Chevron Left Square", category: "All", tags: [] },
  { key: "ChevronRight", label: "Chevron Right", category: "All", tags: [] },
  { key: "ChevronRightCircle", label: "Chevron Right Circle", category: "All", tags: [] },
  { key: "ChevronRightSquare", label: "Chevron Right Square", category: "All", tags: [] },
  { key: "ChevronUp", label: "Chevron Up", category: "All", tags: [] },
  { key: "ChevronUpCircle", label: "Chevron Up Circle", category: "All", tags: [] },
  { key: "ChevronUpSquare", label: "Chevron Up Square", category: "All", tags: [] },
  { key: "ChevronsDown", label: "Chevrons Down", category: "All", tags: [] },
  { key: "ChevronsDownUp", label: "Chevrons Down Up", category: "All", tags: [] },
  { key: "ChevronsLeft", label: "Chevrons Left", category: "All", tags: [] },
  { key: "ChevronsLeftRight", label: "Chevrons Left Right", category: "All", tags: [] },
  { key: "ChevronsLeftRightEllipsis", label: "Chevrons Left Right Ellipsis", category: "All", tags: [] },
  { key: "ChevronsRight", label: "Chevrons Right", category: "All", tags: [] },
  { key: "ChevronsRightLeft", label: "Chevrons Right Left", category: "All", tags: [] },
  { key: "ChevronsUp", label: "Chevrons Up", category: "All", tags: [] },
  { key: "ChevronsUpDown", label: "Chevrons Up Down", category: "All", tags: [] },
  { key: "Church", label: "Church", category: "All", tags: [] },
  { key: "Cigarette", label: "Cigarette", category: "All", tags: [] },
  { key: "CigaretteOff", label: "Cigarette Off", category: "All", tags: [] },
  { key: "Circle", label: "Circle", category: "All", tags: [] },
  { key: "CircleAlert", label: "Circle Alert", category: "All", tags: [] },
  { key: "CircleArrowDown", label: "Circle Arrow Down", category: "All", tags: [] },
  { key: "CircleArrowLeft", label: "Circle Arrow Left", category: "All", tags: [] },
  { key: "CircleArrowOutDownLeft", label: "Circle Arrow Out Down Left", category: "All", tags: [] },
  { key: "CircleArrowOutDownRight", label: "Circle Arrow Out Down Right", category: "All", tags: [] },
  { key: "CircleArrowOutUpLeft", label: "Circle Arrow Out Up Left", category: "All", tags: [] },
  { key: "CircleArrowOutUpRight", label: "Circle Arrow Out Up Right", category: "All", tags: [] },
  { key: "CircleArrowRight", label: "Circle Arrow Right", category: "All", tags: [] },
  { key: "CircleArrowUp", label: "Circle Arrow Up", category: "All", tags: [] },
  { key: "CircleCheck", label: "Circle Check", category: "All", tags: [] },
  { key: "CircleCheckBig", label: "Circle Check Big", category: "All", tags: [] },
  { key: "CircleChevronDown", label: "Circle Chevron Down", category: "All", tags: [] },
  { key: "CircleChevronLeft", label: "Circle Chevron Left", category: "All", tags: [] },
  { key: "CircleChevronRight", label: "Circle Chevron Right", category: "All", tags: [] },
  { key: "CircleChevronUp", label: "Circle Chevron Up", category: "All", tags: [] },
  { key: "CircleDashed", label: "Circle Dashed", category: "All", tags: [] },
  { key: "CircleDivide", label: "Circle Divide", category: "All", tags: [] },
  { key: "CircleDollarSign", label: "Circle Dollar Sign", category: "All", tags: [] },
  { key: "CircleDot", label: "Circle Dot", category: "All", tags: [] },
  { key: "CircleDotDashed", label: "Circle Dot Dashed", category: "All", tags: [] },
  { key: "CircleEllipsis", label: "Circle Ellipsis", category: "All", tags: [] },
  { key: "CircleEqual", label: "Circle Equal", category: "All", tags: [] },
  { key: "CircleFadingArrowUp", label: "Circle Fading Arrow Up", category: "All", tags: [] },
  { key: "CircleFadingPlus", label: "Circle Fading Plus", category: "All", tags: [] },
  { key: "CircleGauge", label: "Circle Gauge", category: "All", tags: [] },
  { key: "CircleHelp", label: "Circle Help", category: "All", tags: [] },
  { key: "CircleMinus", label: "Circle Minus", category: "All", tags: [] },
  { key: "CircleOff", label: "Circle Off", category: "All", tags: [] },
  { key: "CircleParking", label: "Circle Parking", category: "All", tags: [] },
  { key: "CircleParkingOff", label: "Circle Parking Off", category: "All", tags: [] },
  { key: "CirclePause", label: "Circle Pause", category: "All", tags: [] },
  { key: "CirclePercent", label: "Circle Percent", category: "All", tags: [] },
  { key: "CirclePile", label: "Circle Pile", category: "All", tags: [] },
  { key: "CirclePlay", label: "Circle Play", category: "All", tags: [] },
  { key: "CirclePlus", label: "Circle Plus", category: "All", tags: [] },
  { key: "CirclePoundSterling", label: "Circle Pound Sterling", category: "All", tags: [] },
  { key: "CirclePower", label: "Circle Power", category: "All", tags: [] },
  { key: "CircleQuestionMark", label: "Circle Question Mark", category: "All", tags: [] },
  { key: "CircleSlash", label: "Circle Slash", category: "All", tags: [] },
  { key: "CircleSlash2", label: "Circle Slash2", category: "All", tags: [] },
  { key: "CircleSlashed", label: "Circle Slashed", category: "All", tags: [] },
  { key: "CircleSmall", label: "Circle Small", category: "All", tags: [] },
  { key: "CircleStar", label: "Circle Star", category: "All", tags: [] },
  { key: "CircleStop", label: "Circle Stop", category: "All", tags: [] },
  { key: "CircleUser", label: "Circle User", category: "All", tags: [] },
  { key: "CircleUserRound", label: "Circle User Round", category: "All", tags: [] },
  { key: "CircleX", label: "Circle X", category: "All", tags: [] },
  { key: "CircuitBoard", label: "Circuit Board", category: "All", tags: [] },
  { key: "Clapperboard", label: "Clapperboard", category: "All", tags: [] },
  { key: "Clipboard", label: "Clipboard", category: "All", tags: [] },
  { key: "ClipboardCheck", label: "Clipboard Check", category: "All", tags: [] },
  { key: "ClipboardClock", label: "Clipboard Clock", category: "All", tags: [] },
  { key: "ClipboardCopy", label: "Clipboard Copy", category: "All", tags: [] },
  { key: "ClipboardEdit", label: "Clipboard Edit", category: "All", tags: [] },
  { key: "ClipboardMinus", label: "Clipboard Minus", category: "All", tags: [] },
  { key: "ClipboardPaste", label: "Clipboard Paste", category: "All", tags: [] },
  { key: "ClipboardPen", label: "Clipboard Pen", category: "All", tags: [] },
  { key: "ClipboardPenLine", label: "Clipboard Pen Line", category: "All", tags: [] },
  { key: "ClipboardPlus", label: "Clipboard Plus", category: "All", tags: [] },
  { key: "ClipboardSignature", label: "Clipboard Signature", category: "All", tags: [] },
  { key: "ClipboardType", label: "Clipboard Type", category: "All", tags: [] },
  { key: "ClipboardX", label: "Clipboard X", category: "All", tags: [] },
  { key: "Clock", label: "Clock", category: "All", tags: [] },
  { key: "Clock1", label: "Clock1", category: "All", tags: [] },
  { key: "Clock10", label: "Clock10", category: "All", tags: [] },
  { key: "Clock11", label: "Clock11", category: "All", tags: [] },
  { key: "Clock12", label: "Clock12", category: "All", tags: [] },
  { key: "Clock2", label: "Clock2", category: "All", tags: [] },
  { key: "Clock3", label: "Clock3", category: "All", tags: [] },
  { key: "Clock4", label: "Clock4", category: "All", tags: [] },
  { key: "Clock5", label: "Clock5", category: "All", tags: [] },
  { key: "Clock6", label: "Clock6", category: "All", tags: [] },
  { key: "Clock7", label: "Clock7", category: "All", tags: [] },
  { key: "Clock8", label: "Clock8", category: "All", tags: [] },
  { key: "Clock9", label: "Clock9", category: "All", tags: [] },
  { key: "ClockAlert", label: "Clock Alert", category: "All", tags: [] },
  { key: "ClockArrowDown", label: "Clock Arrow Down", category: "All", tags: [] },
  { key: "ClockArrowUp", label: "Clock Arrow Up", category: "All", tags: [] },
  { key: "ClockCheck", label: "Clock Check", category: "All", tags: [] },
  { key: "ClockFading", label: "Clock Fading", category: "All", tags: [] },
  { key: "ClockPlus", label: "Clock Plus", category: "All", tags: [] },
  { key: "ClosedCaption", label: "Closed Caption", category: "All", tags: [] },
  { key: "Cloud", label: "Cloud", category: "All", tags: [] },
  { key: "CloudAlert", label: "Cloud Alert", category: "All", tags: [] },
  { key: "CloudBackup", label: "Cloud Backup", category: "All", tags: [] },
  { key: "CloudCheck", label: "Cloud Check", category: "All", tags: [] },
  { key: "CloudCog", label: "Cloud Cog", category: "All", tags: [] },
  { key: "CloudDownload", label: "Cloud Download", category: "All", tags: [] },
  { key: "CloudDrizzle", label: "Cloud Drizzle", category: "All", tags: [] },
  { key: "CloudFog", label: "Cloud Fog", category: "All", tags: [] },
  { key: "CloudHail", label: "Cloud Hail", category: "All", tags: [] },
  { key: "CloudLightning", label: "Cloud Lightning", category: "All", tags: [] },
  { key: "CloudMoonRain", label: "Cloud Moon Rain", category: "All", tags: [] },
  { key: "CloudOff", label: "Cloud Off", category: "All", tags: [] },
  { key: "CloudRain", label: "Cloud Rain", category: "All", tags: [] },
  { key: "CloudRainWind", label: "Cloud Rain Wind", category: "All", tags: [] },
  { key: "CloudSnow", label: "Cloud Snow", category: "All", tags: [] },
  { key: "CloudSun", label: "Cloud Sun", category: "All", tags: [] },
  { key: "CloudSunRain", label: "Cloud Sun Rain", category: "All", tags: [] },
  { key: "CloudSync", label: "Cloud Sync", category: "All", tags: [] },
  { key: "CloudUpload", label: "Cloud Upload", category: "All", tags: [] },
  { key: "Cloudy", label: "Cloudy", category: "All", tags: [] },
  { key: "Clover", label: "Clover", category: "All", tags: [] },
  { key: "Club", label: "Club", category: "All", tags: [] },

];

export const ICON_KEYS = Object.keys(HABIT_ICON_MAP) as HabitIconKey[];
